/* LIFTOVA Coach Conversation v2.2 — Adaptive-grounded multi-turn coaching + confirmed substitutions. */
const PRISM_ASK_VERSION='2.2',PRISM_ASK_KEY='prismAskHistoryV1';
function prismAskSafe(fn,f=null){try{const v=fn();return v==null?f:v}catch{return f}}
function prismAskHasProAccess(){return prismAskSafe(()=>typeof canAccessFeature==='function'&&canAccessFeature('advanced_analytics'),false)===true}
function prismAskHistory(){try{const v=JSON.parse(localStorage.getItem(PRISM_ASK_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function prismAskSave(row){const rows=prismAskHistory();rows.unshift(row);localStorage.setItem(PRISM_ASK_KEY,JSON.stringify(rows.slice(0,20)))}
function prismAskContext(){const coach=prismAskSafe(()=>prismCoachAnalyze(),null),next=prismAskSafe(()=>prismAdaptiveNextSession(),null),athlete=prismAskSafe(()=>prismAthleteCoachContext(),null);return{coach,next,athlete,prescriptions:next?.prescriptions||coach?.adaptivePrescriptions||[],signal:coach?.snapshot?.checkinSignal||null,weekly:coach?.snapshot?.weekly||null,plateaus:coach?.snapshot?.plateaus||[],decisions:coach?.decisions||[]}}
function prismAskExercise(q,c){q=String(q||'').toLowerCase();return c.prescriptions.find(p=>q.includes(String(p.name||'').toLowerCase())||q.includes(String(p.exerciseId||'').toLowerCase()))||null}
function prismAskPrescriptionText(p){const load=Number(p?.targetWeight)>0?`${p.targetWeight} lb · `:'';return`${p.name}: ${load}${p.workingSets} × ${p.repMin}–${p.repMax}`}
function prismAskRecentContext(c){for(const row of prismAskHistory().slice(0,4)){const ex=prismAskExercise(`${row.question||''} ${row.answer||''}`,c);if(ex)return{exercise:ex,row}}return{exercise:null,row:prismAskHistory()[0]||null}}
function prismAskResolve(q,c){const l=String(q||'').toLowerCase(),explicit=prismAskExercise(q,c),recent=prismAskRecentContext(c),followup=/^(why|how|when|what about|and |should |do i|can i|is it|will it|that|this|it\b)|\b(it|that one|this one|same exercise|next week)\b/.test(l);return{exercise:explicit||((followup||/replace|swap|substitut|alternative|hurts|pain|bother/.test(l))?recent.exercise:null),followup,recent}}
function prismAskAlternatives(ex){if(!ex||typeof getExercise!=='function')return[];const current=getExercise(ex.exerciseId),all=typeof exercises!=='undefined'&&Array.isArray(exercises)?exercises:[];if(!current)return[];let candidates=all.filter(x=>String(x.id)!==String(current.id)&&x.muscle===current.muscle);if(typeof rankExerciseSubstitutions==='function')candidates=rankExerciseSubstitutions(current,candidates)||candidates;return candidates.slice(0,3).map(x=>({id:x.id,name:x.name,reason:x.substitutionReason||x.reason||`Targets ${current.muscle||'the same primary muscle group'}.`}))}
function prismAskConfirmSubstitution(oldId,newId){if(typeof replaceExercise!=='function')return false;replaceExercise(oldId,newId);const oldName=prismAskSafe(()=>getExercise(oldId)?.name,oldId),newName=prismAskSafe(()=>getExercise(newId)?.name,newId);prismAskSave({id:`ask-${Date.now()}`,question:`Replace ${oldName}`,answer:`Replaced ${oldName} with ${newName}.`,why:'You explicitly selected this replacement. Coach used the existing LIFTOVA workout replacement system.',createdAt:new Date().toISOString(),version:PRISM_ASK_VERSION,contextExerciseId:newId});prismAskRender();return true}
function prismAskAnswer(question){if(!prismAskHasProAccess())return null;const q=String(question||'').trim(),l=q.toLowerCase(),c=prismAskContext();if(!q)return null;const r=prismAskResolve(q,c),ex=r.exercise;let answer='',why='',choices=[];
if(ex&&/replace|swap|substitut|alternative|hurts|pain|bother|unavailable/.test(l)){choices=prismAskAlternatives(ex);answer=choices.length?`I found ${choices.length} ranked replacement option${choices.length===1?'':'s'} for ${ex.name}. Choose one below and I’ll use LIFTOVA’s existing workout replacement system.`:`I couldn't find a ranked replacement for ${ex.name} from the current exercise library.`;why='Coach will not change your workout until you explicitly choose a replacement.'}
else if(ex&&/why|weight|hold|increase|lower|target|next/.test(l)){answer=`${prismAskPrescriptionText(ex)}. ${ex.reason}`;why=`${r.followup&&!prismAskExercise(q,c)?`I understood this as a follow-up about ${ex.name}. `:''}This is the authoritative Adaptive Programming prescription.`}
else if(/today|focus|what should i do|next workout/.test(l)){const top=c.prescriptions.slice(0,3);answer=top.length?`Focus on your current adaptive targets: ${top.map(prismAskPrescriptionText).join('; ')}.`:'Follow your scheduled workout and log the working sets so I can build exercise-specific targets.';why=top.length?'These targets use completed training plus progression and recovery signals.':'No current Adaptive prescriptions are available.'}
else if(/recover|tired|fatigue|energy|rest|exhausted/.test(l)){answer=c.signal?(c.signal.load==='conservative'?'Your current recovery context supports a conservative approach; do not force load progression.':'Your recovery context supports the normal plan, with progression only where performance supports it.'):'Complete the Weekly Coach Check-In so I can account for recovery and fatigue.';why=c.signal?.reason||'No current recovery check-in is available.'}
else if(/progress|improv/.test(l)){if(ex){answer=`For ${ex.name}, the current status is ${String(ex.status||'hold').replaceAll('_',' ')}. ${prismAskPrescriptionText(ex)}. ${ex.reason}`;why='I carried the exercise context forward into its Adaptive prescription.'}else{const inc=c.prescriptions.filter(p=>p.status==='increase');answer=c.prescriptions.length?`${inc.length} exercise${inc.length===1?' is':'s are'} ready to progress; ${c.prescriptions.length-inc.length} are being held or managed.`:'I need more completed sessions before I can judge progression.';why='Coach reads the same Adaptive prescriptions used for your next session.'}}
else if(/plateau|stuck|stall/.test(l)){const p=ex?.status==='plateau_hold'?ex:c.prescriptions.find(x=>x.status==='plateau_hold');answer=p?`${p.name} is being held at ${p.targetWeight||'the current load'} while LIFTOVA confirms the plateau.`:'LIFTOVA does not currently detect an active plateau in the available data.';why=p?.reason||'No active plateau signal is present.'}
else if(/30 minute|35 minute|short|time/.test(l)){answer=`For a shorter session, keep the highest-value working sets first and remove optional volume before core movements. Your profile targets about ${c.athlete?.sessionMinutes||30} minutes when available.`;why='This protects core work without changing progression targets solely because time is limited.'}
else if(/schedule|days|week|train/.test(l)){const days=c.signal?.days||c.athlete?.days;answer=days?`Plan around ${days} training day${days===1?'':'s'} this week.`:'Set your Athlete Profile or Weekly Coach Check-In so I know how many days you can train.';why=c.signal?.days?'This uses your Weekly Coach Check-In.':'This uses your Athlete Profile when available.'}
else if(c.decisions.length){const d=c.decisions[0];answer=`Your highest-priority Coach recommendation is: ${d.action}`;why=d.why}else{answer='Ask about today’s workout, progression, recovery, a plateau, your schedule, a specific exercise, or replacing an exercise.';why='Coach only answers from saved LIFTOVA training context.'}
const row={id:`ask-${Date.now()}`,question:q,answer,why,choices,choiceSourceExerciseId:choices.length?ex?.exerciseId:null,createdAt:new Date().toISOString(),version:PRISM_ASK_VERSION,contextExerciseId:ex?.exerciseId||null,followup:r.followup};prismAskSave(row);return row}
function prismAskSubmit(e){e.preventDefault();if(!prismAskHasProAccess())return prismAskRender();const i=e.currentTarget.elements.question,q=i.value.trim();if(!q)return;prismAskAnswer(q);i.value='';prismAskRender()}
function prismAskQuick(q){if(prismAskHasProAccess()){prismAskAnswer(q);prismAskRender()}}
function prismAskClear(){localStorage.removeItem(PRISM_ASK_KEY);prismAskRender()}
function prismAskUpgrade(){if(typeof showPrismPro==='function')return showPrismPro();document.getElementById('prismProExperience')?.scrollIntoView({behavior:'smooth',block:'start'})}
function prismAskFreePreview(){return`<div class="card prism-ask-upgrade"><span class="journey-eyebrow">LIFTOVA PRO · COACH PREVIEW</span><h3>Ask your Coach</h3><p class="small">Pro Coach explains targets, recovery, plateaus and substitutions using your training data.</p><button type="button" class="primary" style="width:100%;min-height:50px;border:0;border-radius:12px;font-weight:800" onclick="prismAskUpgrade()">Unlock LIFTOVA Coach</button></div>`}
function prismAskRender(){const host=document.getElementById('prismAsk');if(!host)return;if(!prismAskHasProAccess()){host.innerHTML=prismAskFreePreview();return}const rows=prismAskHistory();host.innerHTML=`<div class="card"><span class="journey-eyebrow">LIFTOVA PRO · COACH CONVERSATION V2.2</span><h3>Ask Coach</h3><p class="small">Coach keeps recent context and uses the same Adaptive Programming and exercise-replacement systems as your workout.</p><div class="prism-coach-actions"><button type="button" onclick="prismAskQuick('What should I focus on today?')">Today’s focus</button><button type="button" onclick="prismAskQuick('Am I progressing?')">Am I progressing?</button><button type="button" onclick="prismAskQuick('How is my recovery?')">Recovery</button></div><form onsubmit="prismAskSubmit(event)"><label>Question<input name="question" maxlength="220" placeholder="Can I replace my chest press?" required></label><button type="submit">Ask Coach</button></form>${rows.slice(0,8).map(r=>`<article class="prism-coach-decision"><h4>${escapeHTML(r.question)}</h4><p><strong>${escapeHTML(r.answer)}</strong></p><p class="small">Why: ${escapeHTML(r.why)}</p>${(r.choices||[]).map(x=>`<button type="button" onclick="prismAskConfirmSubstitution('${escapeAttribute(r.choiceSourceExerciseId)}','${escapeAttribute(x.id)}')">Use ${escapeHTML(x.name)}</button><p class="small">${escapeHTML(x.reason)}</p>`).join('')}</article>`).join('')}${rows.length?`<button type="button" onclick="prismAskClear()">Clear conversation</button>`:''}</div>`}
function prismAskMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismAsk');if(!host){host=document.createElement('div');host.id='prismAsk';const adaptive=document.getElementById('prismAdaptiveProgramming');adaptive?adaptive.insertAdjacentElement('afterend',host):screen.appendChild(host)}prismAskRender()}
window.prismAskAnswer=prismAskAnswer;window.prismAskRender=prismAskRender;window.prismAskMount=prismAskMount;window.prismAskSubmit=prismAskSubmit;window.prismAskQuick=prismAskQuick;window.prismAskClear=prismAskClear;window.prismAskUpgrade=prismAskUpgrade;window.prismAskConfirmSubstitution=prismAskConfirmSubstitution;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismAsk){const original=showOverallProgress;showOverallProgress=function(){original();prismAskMount()};showOverallProgress.__prismAsk=true}
