/* LIFTOVA Coach Conversation v2.0 — evidence-grounded Q&A over authoritative Adaptive Programming decisions. */
const PRISM_ASK_VERSION='2.0';
const PRISM_ASK_KEY='prismAskHistoryV1';
function prismAskSafe(fn,fallback=null){try{const v=fn();return v==null?fallback:v}catch{return fallback}}
function prismAskHasProAccess(){return prismAskSafe(()=>typeof canAccessFeature==='function'&&canAccessFeature('advanced_analytics'),false)===true;}
function prismAskHistory(){try{const v=JSON.parse(localStorage.getItem(PRISM_ASK_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function prismAskSave(row){const rows=prismAskHistory();rows.unshift(row);localStorage.setItem(PRISM_ASK_KEY,JSON.stringify(rows.slice(0,20)));}
function prismAskContext(){const coach=prismAskSafe(()=>typeof prismCoachAnalyze==='function'?prismCoachAnalyze():null,null),next=prismAskSafe(()=>typeof prismAdaptiveNextSession==='function'?prismAdaptiveNextSession():null,null),athlete=prismAskSafe(()=>typeof prismAthleteCoachContext==='function'?prismAthleteCoachContext():null,null);return {coach,next,athlete,prescriptions:next?.prescriptions||coach?.adaptivePrescriptions||[],signal:coach?.snapshot?.checkinSignal||null,weekly:coach?.snapshot?.weekly||null,plateaus:coach?.snapshot?.plateaus||[],decisions:coach?.decisions||[]};}
function prismAskExercise(question,c){const q=String(question||'').toLowerCase();return c.prescriptions.find(p=>q.includes(String(p.name||'').toLowerCase())||q.includes(String(p.exerciseId||'').toLowerCase()))||null;}
function prismAskPrescriptionText(p){const load=Number(p?.targetWeight)>0?`${p.targetWeight} lb · `:'';return `${p.name}: ${load}${p.workingSets} × ${p.repMin}–${p.repMax}`;}
function prismAskAnswer(question){if(!prismAskHasProAccess())return null;const q=String(question||'').trim(),l=q.toLowerCase(),c=prismAskContext();if(!q)return null;const ex=prismAskExercise(q,c);let answer='',why='';
if(ex&&/why|weight|hold|increase|lower|target|next/.test(l)){answer=`${prismAskPrescriptionText(ex)}. ${ex.reason}`;why='This is the authoritative Adaptive Programming prescription used by Coach and your next-session guidance.';}
else if(/today|focus|what should i do|next workout/.test(l)){const top=c.prescriptions.slice(0,3);if(top.length){answer=`Focus on executing your current adaptive targets cleanly: ${top.map(prismAskPrescriptionText).join('; ')}.`;why='These targets combine completed training with current progression, recovery, fatigue and plateau signals.';}else{answer='Follow your scheduled workout and log the working sets. I need completed training before I can give exercise-specific next-session targets.';why='No current Adaptive Programming prescriptions are available.';}}
else if(/recover|tired|fatigue|energy|rest|exhausted/.test(l)){if(c.signal){answer=c.signal.load==='conservative'?'Your current recovery context supports a conservative training approach. I would not force load progression right now.':c.signal.load==='progressive'?'Your current recovery context supports normal progression where performance data is also ready.':'Your recovery context supports the normal plan, with progression only where performance supports it.';why=c.signal.reason||'This uses your latest Weekly Coach Check-In.';}else{answer='Complete the Weekly Coach Check-In so I can account for recovery and fatigue in your next targets.';why='No current recovery check-in is available.';}}
else if(/am i progressing|progressing|improving|progress/.test(l)){const inc=c.prescriptions.filter(p=>p.status==='increase'),managed=c.prescriptions.filter(p=>p.status!=='increase');if(c.prescriptions.length){answer=`Your next-session data has ${inc.length} exercise${inc.length===1?'':'s'} ready to progress and ${managed.length} being held or managed.${inc.length?' '+inc.slice(0,2).map(p=>`${p.name} is ready for ${p.targetWeight} lb.`).join(' '):' No load increase is supported right now.'}`;why='Coach is reading the same Adaptive Programming prescriptions that drive your next-session targets.';}else{answer='I need more completed sessions before I can judge progression from your training data.';why='No current exercise prescriptions are available.';}}
else if(/increase|weight|heavier/.test(l)){const d=c.prescriptions.find(p=>p.status==='increase')||c.decisions.find(x=>x.meta?.targetWeight>0);if(d?.exerciseId){answer=`${prismAskPrescriptionText(d)}. ${d.reason}`;why='Adaptive Programming currently supports this progression.';}else if(d){answer=d.action;why=d.why;}else{answer='I do not have a supported load increase to recommend yet. Keep logging completed sets so progression can be based on actual performance.';why='No current adaptive prescription supports an increase.';}}
else if(/plateau|stuck|stall/.test(l)){const p=c.prescriptions.find(x=>x.status==='plateau_hold'),legacy=c.plateaus?.[0];if(p){answer=`${p.name} is currently being held at ${p.targetWeight||'the current load'} while we confirm the plateau before making a larger change.`;why=p.reason;}else if(legacy){const name=legacy.name||prismAskSafe(()=>getExercise(legacy.id)?.name,'that exercise');answer=`LIFTOVA currently flags ${name} for review. Keep the next change conservative or review a ranked substitute.`;why=legacy.reason||'Recent sessions show limited progression.';}else{answer='LIFTOVA does not currently detect a plateau in the available training data.';why='No active plateau signal is present.';}}
else if(/30 minute|35 minute|short|time/.test(l)){const mins=c.athlete?.sessionMinutes||30;answer=`For a shorter session, keep the highest-value working sets first and remove optional volume before core movements. Your Athlete Profile targets about ${mins} minutes when available.`;why='This preserves the most important training work instead of changing your progression targets just because time is limited.';}
else if(/schedule|days|week|train/.test(l)){const days=c.signal?.days||c.athlete?.days;if(days){answer=`Plan around ${days} training day${days===1?'':'s'}${c.signal?.days&&c.athlete?.days&&c.signal.days<c.athlete.days?` this week instead of your normal ${c.athlete.days}`:''}.`;why=c.signal?.days?'This uses your Weekly Coach Check-In and Athlete Profile.':'This uses your Athlete Profile.';}else{answer='Set your Athlete Profile or Weekly Coach Check-In so I know how many days you can train.';why='No schedule context is available.';}}
else if(/last week|changed|change/.test(l)){const workouts=Number(c.weekly?.workouts??c.weekly?.workoutsCompleted??0),sets=Number(c.weekly?.sets??c.weekly?.workingSets??0);if(workouts||sets){answer=`Your current weekly baseline is ${workouts} completed workout${workouts===1?'':'s'} and ${sets} working set${sets===1?'':'s'}. Your next targets reflect that completed work plus current recovery and progression signals.`;why='LIFTOVA uses completed training rather than planned training as the baseline.';}else{answer='I do not have enough weekly summary data yet to make a useful week-to-week comparison.';why='More completed training is needed.';}}
else if(/goal|muscle|hypertrophy|strength/.test(l)){if(c.athlete){answer=c.athlete.goal==='strength'?'Your Athlete Profile is strength-focused, so supported load progression and repeatable performance stay central.':c.athlete.goal==='hypertrophy'?'Your Athlete Profile is muscle-growth focused, so productive working sets, target reps and gradual overload stay central.':`Your Athlete Profile goal is ${c.athlete.goal}. Coach uses that as a programming filter.`;why=c.athlete.summary;}else{answer='Complete your Athlete Profile so I can answer goal-specific coaching questions.';why='No persistent Athlete Profile is available.';}}
else if(c.decisions.length){const d=c.decisions[0];answer=`Your highest-priority Coach recommendation right now is: ${d.action}`;why=d.why;}
else{answer='I am still gathering training evidence. Ask about today’s workout, progression, recovery, a plateau, your schedule, or a specific exercise.';why='Coach only answers from saved LIFTOVA training context.';}
const row={id:`ask-${Date.now()}`,question:q,answer,why,createdAt:new Date().toISOString(),version:PRISM_ASK_VERSION};prismAskSave(row);return row;}
function prismAskSubmit(event){event.preventDefault();if(!prismAskHasProAccess()){prismAskRender();return;}const input=event.currentTarget.elements.question,q=input.value.trim();if(!q)return;prismAskAnswer(q);input.value='';prismAskRender();}
function prismAskQuick(question){if(!prismAskHasProAccess())return;prismAskAnswer(question);prismAskRender();}
function prismAskClear(){localStorage.removeItem(PRISM_ASK_KEY);prismAskRender();}
function prismAskUpgrade(){if(typeof showPrismPro==='function'){showPrismPro();return;}document.getElementById('prismProExperience')?.scrollIntoView({behavior:'smooth',block:'start'});}
function prismAskFreePreview(){return `<div class="card prism-ask-upgrade"><span class="journey-eyebrow">LIFTOVA PRO · COACH PREVIEW</span><h3>Ask your Coach</h3><p class="small">Pro Coach can explain your next targets, progression, recovery and plateaus using your saved training data.</p><button type="button" class="primary" style="width:100%;min-height:50px;border:0;border-radius:12px;font-weight:800" onclick="prismAskUpgrade()">Unlock LIFTOVA Coach</button></div>`;}
function prismAskRender(){const host=document.getElementById('prismAsk');if(!host)return;if(!prismAskHasProAccess()){host.innerHTML=prismAskFreePreview();return;}const rows=prismAskHistory();host.innerHTML=`<div class="card"><span class="journey-eyebrow">LIFTOVA PRO · COACH CONVERSATION V2</span><h3>Ask Coach</h3><p class="small">Ask about your workout, progression, recovery, plateaus, schedule or a specific exercise. Coach explains the same Adaptive Programming decisions used for your next workout.</p><div class="prism-coach-actions"><button type="button" onclick="prismAskQuick('What should I focus on today?')">Today’s focus</button><button type="button" onclick="prismAskQuick('Am I progressing?')">Am I progressing?</button><button type="button" onclick="prismAskQuick('How is my recovery?')">Recovery</button></div><form onsubmit="prismAskSubmit(event)"><label>Question<input name="question" maxlength="220" placeholder="Why are you holding my chest press?" required></label><button type="submit">Ask Coach</button></form>${rows.slice(0,8).map(r=>`<article class="prism-coach-decision"><h4>${escapeHTML(r.question)}</h4><p><strong>${escapeHTML(r.answer)}</strong></p><p class="small">Why: ${escapeHTML(r.why)}</p></article>`).join('')}${rows.length?`<button type="button" onclick="prismAskClear()">Clear conversation</button>`:''}</div>`;}
function prismAskMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismAsk');if(!host){host=document.createElement('div');host.id='prismAsk';const adaptive=document.getElementById('prismAdaptiveProgramming');if(adaptive)adaptive.insertAdjacentElement('afterend',host);else screen.appendChild(host);}prismAskRender();}
window.prismAskAnswer=prismAskAnswer;window.prismAskRender=prismAskRender;window.prismAskMount=prismAskMount;window.prismAskSubmit=prismAskSubmit;window.prismAskQuick=prismAskQuick;window.prismAskClear=prismAskClear;window.prismAskUpgrade=prismAskUpgrade;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismAsk){const original=showOverallProgress;showOverallProgress=function(){original();prismAskMount();};showOverallProgress.__prismAsk=true;}
