/* PRISM Coach Today v1 — one daily command center for the Pro coaching loop. */
const PRISM_COACH_TODAY_VERSION='1.0';
function prismTodaySafe(fn,fallback=null){try{const v=fn();return v==null?fallback:v}catch{return fallback}}
function prismTodayHasPro(){return prismTodaySafe(()=>typeof canAccessFeature==='function'&&canAccessFeature('coach_engine'),false)===true;}
function prismTodayData(){const readiness=prismTodaySafe(()=>typeof prismReadinessAnalyze==='function'?prismReadinessAnalyze():null,null),pre=prismTodaySafe(()=>typeof prismPreWorkoutPlan==='function'?prismPreWorkoutPlan():null,null),next=prismTodaySafe(()=>typeof prismNextSessionPlan==='function'?prismNextSessionPlan():null,null),coach=prismTodaySafe(()=>typeof prismCoachAnalyze==='function'?prismCoachAnalyze():null,null),fatigue=prismTodaySafe(()=>typeof prismAdaptiveFatigueSignals==='function'?prismAdaptiveFatigueSignals():null,null);const target=pre?.targets?.[0]||null,priority=next?.actions?.[0]||coach?.decisions?.[0]||null;let state='READY',headline='Your Coach is ready',action='Open today’s workout and follow your planned targets.',why='PRISM will combine your saved performance and Coach context as you train.';if(readiness){state=readiness.mode;headline=readiness.title;action=readiness.guidance;why=readiness.reasons?.[0]||why;}if(priority){action=priority.action||action;why=priority.why||why;}return {readiness,pre,next,coach,fatigue,target,priority,state,headline,action,why};}
function prismTodayOpenWorkout(){const first=document.querySelector('[onclick*="openWorkout"],button[data-workout],.workout-card button');if(first){first.click();return;}if(typeof showHome==='function')showHome();}
function prismTodayRender(){const host=document.getElementById('prismCoachToday');if(!host)return;if(!prismTodayHasPro()){host.innerHTML='';host.classList.add('hidden');return;}host.classList.remove('hidden');const d=prismTodayData(),score=d.readiness?.score;host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO · COACH TODAY</span><div class="journey-summary"><span>${escapeHTML(d.state)}</span><strong>${score?`${score}/5 readiness`:'TODAY'}</strong></div><h3>${escapeHTML(d.headline)}</h3><p><strong>${escapeHTML(d.action)}</strong></p><p class="small">Why: ${escapeHTML(d.why)}</p>${d.target?`<article class="prism-coach-decision"><div class="journey-summary"><span>FIRST TARGET</span><strong>${escapeHTML(d.target.mode)}</strong></div><h4>${escapeHTML(d.target.name)}</h4><p><strong>${d.target.weight>0?`${escapeHTML(String(d.target.weight))} lb · `:''}${d.target.min}–${d.target.max} reps</strong></p></article>`:''}${d.fatigue?.top?`<article class="prism-coach-decision"><div class="journey-summary"><span>FATIGUE WATCH</span><strong>MONITOR</strong></div><h4>${escapeHTML(d.fatigue.top.name)}</h4><p class="small">${escapeHTML(String(d.fatigue.top.count))} recent fatigue signals. Coach will keep progression conservative until performance stabilizes.</p></article>`:''}<button type="button" class="primary" style="width:100%;min-height:50px;border:0;border-radius:12px;font-weight:800" onclick="prismTodayOpenWorkout()">Start Today’s Training</button></div>`;}
function prismTodayMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismCoachToday');if(!host){host=document.createElement('div');host.id='prismCoachToday';const ask=document.getElementById('prismAsk');if(ask)ask.insertAdjacentElement('beforebegin',host);else screen.prepend(host);}prismTodayRender();}
window.prismTodayData=prismTodayData;window.prismTodayRender=prismTodayRender;window.prismTodayMount=prismTodayMount;window.prismTodayOpenWorkout=prismTodayOpenWorkout;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismToday){const original=showOverallProgress;showOverallProgress=function(){original();setTimeout(prismTodayMount,0);};showOverallProgress.__prismToday=true;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(prismTodayMount,500),{once:true});else setTimeout(prismTodayMount,500);