/* PRISM Coach Engine v1.1 — deterministic, explainable coaching + user-controlled actions. */
const PRISM_COACH_VERSION='1.1';
const PRISM_COACH_ACTIONS_KEY='prismCoachActionsV1';
function prismCoachSafe(fn,fallback=null){try{const v=fn();return v==null?fallback:v}catch{return fallback}}
function prismCoachSnapshot(){
  const weekly=prismCoachSafe(()=>typeof prismWeeklySummaryData==='function'?prismWeeklySummaryData():null,null);
  const plateaus=prismCoachSafe(()=>typeof prismPlateauAnalyze==='function'?prismPlateauAnalyze():[],[])||[];
  const phase=prismCoachSafe(()=>typeof prismActivePhase==='function'?prismActivePhase():null,null);
  const measurements=prismCoachSafe(()=>typeof prismMeasurementRead==='function'?prismMeasurementRead():[],[])||[];
  const history=Array.isArray(window.workoutHistory)?window.workoutHistory:(typeof workoutHistory!=='undefined'&&Array.isArray(workoutHistory)?workoutHistory:[]);
  const sessions=history.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));
  const recent=sessions.slice(0,8),exerciseRows=new Map();
  for(const s of recent)for(const ex of s.exercises||[]){const valid=(ex.sets||[]).filter(x=>Number(x.weight)>0&&Number(x.reps)>0);if(!valid.length)continue;const row=exerciseRows.get(ex.id)||{id:ex.id,name:prismCoachSafe(()=>getExercise(ex.id)?.name,ex.name||ex.id),sessions:0,sets:0,volume:0,lastDate:s.date};row.sessions++;row.sets+=valid.length;row.volume+=valid.reduce((n,x)=>n+Number(x.weight)*Number(x.reps),0);exerciseRows.set(ex.id,row);}
  return {version:PRISM_COACH_VERSION,generatedAt:new Date().toISOString(),history,sessions,recent,weekly,plateaus,phase,measurements,exercises:[...exerciseRows.values()]};
}
function prismCoachDecision(id,priority,title,action,why,confidence,source,meta={}){return {id,priority,title,action,why,confidence,source,meta};}
function prismCoachProgressionDecisions(snapshot){const out=[];for(const ex of snapshot.exercises.slice(0,12)){const p=prismCoachSafe(()=>typeof progressionSuggestion==='function'?progressionSuggestion(ex.id):null,null);if(!p)continue;if(p.status==='ready'&&Number(p.weight)>0)out.push(prismCoachDecision(`progress-${ex.id}`,70,`Progress ${ex.name}`,`Try ${p.weight} lb for ${p.range?.min||8}–${p.range?.max||12} reps next time.`,`Your saved performance reached PRISM's progression threshold.`,.9,'smart_progression',{exerciseId:ex.id,targetWeight:p.weight,repMin:p.range?.min||8,repMax:p.range?.max||12,action:p.action||'hold'}));else if(p.lastWeight)out.push(prismCoachDecision(`hold-${ex.id}`,35,`Keep ${ex.name} steady`,`Keep ${p.lastWeight} lb and aim to improve reps before adding weight.`,`Your recent sets have not reached the progression threshold yet.`,.8,'smart_progression',{exerciseId:ex.id,targetWeight:p.lastWeight,repMin:p.range?.min||8,repMax:p.range?.max||12,action:'hold'}));}return out;}
function prismCoachPlateauDecisions(snapshot){const rows=Array.isArray(snapshot.plateaus)?snapshot.plateaus:[];return rows.slice(0,4).map((p,i)=>{const name=p.name||prismCoachSafe(()=>getExercise(p.id)?.name,p.id||'this exercise');return prismCoachDecision(`plateau-${p.id||i}`,90,`${name} may be stalled`,`Keep the next change conservative: hold the load, improve execution/reps, or choose a ranked substitute.`,p.reason||`PRISM detected repeated sessions without meaningful progression.`,.85,'plateau_detection',{exerciseId:p.id});});}
function prismCoachPhaseDecision(snapshot){const p=snapshot.phase;if(!p)return [];const label=(window.PRISM_GOAL_NAMES||{})[p.type]||p.type||'goal',start=new Date(`${p.startDate}T12:00:00`),days=Math.max(0,Math.floor((Date.now()-start.getTime())/86400000));return [prismCoachDecision('phase-focus',20,`${label} phase: week ${Math.floor(days/7)+1}`,`Keep training decisions aligned with your current ${label.toLowerCase()} phase while PRISM gathers more outcome data.`,`Your active goal phase started ${p.startDate}.`,.7,'phase_analysis',{phaseId:p.id})];}
function prismCoachWeeklyDecision(snapshot){const w=snapshot.weekly;if(!w)return [];const workouts=Number(w.workouts??w.workoutsCompleted??0),sets=Number(w.sets??w.workingSets??0);if(!workouts&&!sets)return [];return [prismCoachDecision('weekly-focus',40,'Use this week as the baseline',`Build the next week from ${workouts} completed workout${workouts===1?'':'s'} and ${sets} working set${sets===1?'':'s'}.`,`PRISM Coach uses completed training—not planned training—as its baseline.`,.75,'weekly_summary')];}
function prismCoachRank(decisions){const seen=new Set();return decisions.filter(d=>{const key=`${d.source}:${d.meta?.exerciseId||d.id}`;if(seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>b.priority-a.priority).slice(0,5);}
function prismCoachAnalyze(){const snapshot=prismCoachSnapshot(),decisions=prismCoachRank([...prismCoachPlateauDecisions(snapshot),...prismCoachProgressionDecisions(snapshot),...prismCoachWeeklyDecision(snapshot),...prismCoachPhaseDecision(snapshot)]);return {snapshot,decisions};}
function prismCoachConfidenceLabel(v){return v>=.85?'High':v>=.7?'Moderate':'Early';}
function prismCoachHasProAccess(){return typeof canAccessFeature!=='function'||canAccessFeature('advanced_analytics');}
function prismCoachReadActions(){try{const v=JSON.parse(localStorage.getItem(PRISM_COACH_ACTIONS_KEY)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch{return {}}}
function prismCoachSaveAction(id,value){const actions=prismCoachReadActions();actions[id]={...value,updatedAt:new Date().toISOString()};localStorage.setItem(PRISM_COACH_ACTIONS_KEY,JSON.stringify(actions));}
function prismCoachApplyTarget(decisionId){const d=prismCoachAnalyze().decisions.find(x=>x.id===decisionId);if(!d?.meta?.exerciseId||!(Number(d.meta.targetWeight)>0))return;if(typeof tracking==='undefined'||typeof saveTracking!=='function')return;tracking.manualTargets=tracking.manualTargets||{};const key=typeof overloadKey==='function'?overloadKey(d.meta.exerciseId):d.meta.exerciseId;tracking.manualTargets[key]=Number(d.meta.targetWeight);if(typeof overloadTargets!=='undefined'){overloadTargets[key]=Number(d.meta.targetWeight);localStorage.setItem('overloadTargetsV1',JSON.stringify(overloadTargets));}saveTracking();prismCoachSaveAction(d.id,{status:'applied',exerciseId:d.meta.exerciseId,targetWeight:Number(d.meta.targetWeight)});prismCoachRender();}
function prismCoachKeepTarget(decisionId){const d=prismCoachAnalyze().decisions.find(x=>x.id===decisionId);if(!d)return;prismCoachSaveAction(d.id,{status:'kept',exerciseId:d.meta?.exerciseId||null,targetWeight:Number(d.meta?.targetWeight)||null});prismCoachRender();}
function prismCoachDismiss(decisionId){const d=prismCoachAnalyze().decisions.find(x=>x.id===decisionId);if(!d)return;prismCoachSaveAction(d.id,{status:'dismissed',exerciseId:d.meta?.exerciseId||null});prismCoachRender();}
function prismCoachSubstitute(exerciseId){if(!exerciseId)return;if(typeof rankExerciseSubstitutions==='function'){const ranked=rankExerciseSubstitutions(exerciseId)||[],best=ranked[0];if(best?.exercise){alert(`${best.exercise.name}\n\n${best.reason||'Ranked by PRISM as a similar alternative.'}`);return;}}if(typeof showLibrary==='function')showLibrary();}
function prismCoachActionsHTML(d){const saved=prismCoachReadActions()[d.id],buttons=[];if(Number(d.meta?.targetWeight)>0&&d.meta?.exerciseId)buttons.push(`<button type="button" onclick="prismCoachApplyTarget('${escapeAttribute(d.id)}')">Apply ${escapeHTML(d.meta.targetWeight)} lb target</button>`,`<button type="button" onclick="prismCoachKeepTarget('${escapeAttribute(d.id)}')">Keep current target</button>`);if(d.source==='plateau_detection'&&d.meta?.exerciseId)buttons.push(`<button type="button" onclick="prismCoachSubstitute('${escapeAttribute(d.meta.exerciseId)}')">Show substitute</button>`);buttons.push(`<button type="button" onclick="prismCoachDismiss('${escapeAttribute(d.id)}')">Not now</button>`);const status=saved?.status==='applied'?`<p class="small"><strong>✓ Applied.</strong> This target will appear in the workout. You can still change it anytime.</p>`:saved?.status==='kept'?`<p class="small"><strong>✓ Current target kept.</strong></p>`:saved?.status==='dismissed'?`<p class="small">Recommendation dismissed for now.</p>`:'';return `<div class="prism-coach-actions">${buttons.join('')}</div>${status}`;}
function prismCoachRender(){const host=document.getElementById('prismCoach');if(!host)return;if(!prismCoachHasProAccess()){host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO ✦</span><h3>PRISM Coach</h3><p class="small">Turn your saved training into prioritized next-step coaching instead of isolated statistics.</p><button type="button" onclick="showProPreview('coach_engine')">Preview PRISM Coach</button></div>`;return;}const result=prismCoachAnalyze();if(!result.decisions.length){host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM COACH · V1.1</span><h3>Your coaching plan is building</h3><p class="small">Complete and save workouts so PRISM can make evidence-based recommendations from your own training history.</p></div>`;return;}host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM COACH · V1.1</span><h3>Your next priorities</h3><p class="small">PRISM Coach combines your saved training signals into a short, prioritized plan. Nothing changes until you choose an action.</p>${result.decisions.map((d,i)=>`<article class="prism-coach-decision"><div class="journey-summary"><span>${i===0?'TOP PRIORITY':`PRIORITY ${i+1}`}</span><strong>${escapeHTML(prismCoachConfidenceLabel(d.confidence))} confidence</strong></div><h4>${escapeHTML(d.title)}</h4><p><strong>${escapeHTML(d.action)}</strong></p><p class="small">Why: ${escapeHTML(d.why)}</p>${prismCoachActionsHTML(d)}</article>`).join('')}</div>`;}
function prismCoachMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismCoach');if(!host){host=document.createElement('div');host.id='prismCoach';screen.insertAdjacentElement('afterbegin',host);}prismCoachRender();}
window.prismCoachSnapshot=prismCoachSnapshot;window.prismCoachAnalyze=prismCoachAnalyze;window.prismCoachRender=prismCoachRender;window.prismCoachMount=prismCoachMount;window.prismCoachApplyTarget=prismCoachApplyTarget;window.prismCoachKeepTarget=prismCoachKeepTarget;window.prismCoachDismiss=prismCoachDismiss;window.prismCoachSubstitute=prismCoachSubstitute;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismCoach){const original=showOverallProgress;showOverallProgress=function(){original();prismCoachMount();};showOverallProgress.__prismCoach=true;}