/* PRISM Coach Check-In v1 — local, user-controlled context for Coach. */
const PRISM_CHECKIN_KEY='prismCoachCheckinsV1';
function prismCheckinWeek(){return typeof weekStart==='function'?weekStart(new Date()):new Date().toISOString().slice(0,10);}
function prismCheckinRead(){try{const v=JSON.parse(localStorage.getItem(PRISM_CHECKIN_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function prismCheckinLatest(){return prismCheckinRead()[0]||null;}
function prismCheckinCurrent(){return prismCheckinRead().find(x=>x.week===prismCheckinWeek())||null;}
function prismCheckinSave(values){const row={week:prismCheckinWeek(),recovery:values.recovery,energy:values.energy,difficulty:values.difficulty,days:Number(values.days),limitations:String(values.limitations||'').trim().slice(0,300),updatedAt:new Date().toISOString()};if(!['poor','good','great'].includes(row.recovery)||!['low','normal','high'].includes(row.energy)||!['easy','right','hard'].includes(row.difficulty)||!Number.isInteger(row.days)||row.days<1||row.days>7)return false;const rows=prismCheckinRead().filter(x=>x.week!==row.week);rows.unshift(row);localStorage.setItem(PRISM_CHECKIN_KEY,JSON.stringify(rows.slice(0,26)));return row;}
function prismCheckinCoachSignal(row=prismCheckinCurrent()||prismCheckinLatest()){if(!row)return null;let load='normal',reason='Recovery and difficulty look appropriate for normal progression.';if(row.recovery==='poor'||row.energy==='low'||row.difficulty==='hard'){load='conservative';reason='Your check-in suggests recovery or training stress is limiting you, so Coach should avoid aggressive progression.';}else if(row.recovery==='great'&&row.energy==='high'&&row.difficulty==='easy'){load='progressive';reason='Recovery and energy are high while training feels easy, so normal progression can be considered when performance data agrees.';}return {load,reason,days:row.days,limitations:row.limitations,week:row.week};}
function prismCheckinHandle(event){event.preventDefault();const f=event.currentTarget,saved=prismCheckinSave({recovery:f.recovery.value,energy:f.energy.value,difficulty:f.difficulty.value,days:f.days.value,limitations:f.limitations.value});const status=document.getElementById('prismCheckinStatus');if(!saved){if(status)status.textContent='Complete each check-in choice.';return;}if(status)status.textContent='Check-in saved. PRISM Coach will use it with your training data.';if(typeof prismCoachRender==='function')prismCoachRender();prismCheckinRender();}
function prismCheckinRender(){const host=document.getElementById('prismCoachCheckin');if(!host)return;if(typeof canAccessFeature==='function'&&!canAccessFeature('advanced_analytics')){host.innerHTML='';return;}const c=prismCheckinCurrent();host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM COACH · WEEKLY CHECK-IN</span><h3>${c?'Update this week':'How are you doing this week?'}</h3><p class="small">Your answers add recovery and schedule context that workout numbers cannot show. They stay on this device.</p><form onsubmit="prismCheckinHandle(event)"><label>Recovery<select name="recovery" required><option value="">Choose</option><option value="poor" ${c?.recovery==='poor'?'selected':''}>Poor</option><option value="good" ${c?.recovery==='good'?'selected':''}>Good</option><option value="great" ${c?.recovery==='great'?'selected':''}>Great</option></select></label><label>Energy<select name="energy" required><option value="">Choose</option><option value="low" ${c?.energy==='low'?'selected':''}>Low</option><option value="normal" ${c?.energy==='normal'?'selected':''}>Normal</option><option value="high" ${c?.energy==='high'?'selected':''}>High</option></select></label><label>Training difficulty<select name="difficulty" required><option value="">Choose</option><option value="easy" ${c?.difficulty==='easy'?'selected':''}>Too easy</option><option value="right" ${c?.difficulty==='right'?'selected':''}>About right</option><option value="hard" ${c?.difficulty==='hard'?'selected':''}>Too hard</option></select></label><label>Days available next week<input name="days" type="number" min="1" max="7" step="1" value="${c?.days||4}" required></label><label>Pain, limitations, or anything Coach should account for?<textarea name="limitations" maxlength="300" placeholder="Optional">${escapeHTML(c?.limitations||'')}</textarea></label><button type="submit">${c?'Update check-in':'Save check-in'}</button><output id="prismCheckinStatus" role="status"></output></form></div>`;}
function prismCheckinMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismCoachCheckin');if(!host){host=document.createElement('div');host.id='prismCoachCheckin';const coach=document.getElementById('prismCoach');if(coach)coach.insertAdjacentElement('afterend',host);else screen.insertAdjacentElement('afterbegin',host);}prismCheckinRender();}
window.prismCheckinRead=prismCheckinRead;window.prismCheckinLatest=prismCheckinLatest;window.prismCheckinCurrent=prismCheckinCurrent;window.prismCheckinSave=prismCheckinSave;window.prismCheckinCoachSignal=prismCheckinCoachSignal;window.prismCheckinRender=prismCheckinRender;window.prismCheckinMount=prismCheckinMount;window.prismCheckinHandle=prismCheckinHandle;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismCheckin){const original=showOverallProgress;showOverallProgress=function(){original();prismCheckinMount();};showOverallProgress.__prismCheckin=true;}