// Final visual/branding cleanup for MYLIFTCOACH.
// Presentation only; PRISM-prefixed storage keys/functions/classes remain untouched for compatibility.
(() => {
  'use strict';
  const BRAND='MYLIFTCOACH';
  const ICON='images/liftova-icon.svg?v=8';
  const replaceBrand=text=>typeof text==='string'?text.replace(/PRISM/g,BRAND).replace(/Prism/g,BRAND).replace(/LIFTOVA/g,BRAND).replace(/Liftova/g,BRAND):text;
  function updateMetadata(){document.title='MYLIFTCOACH · Train · Track · Progress';const appleTitle=document.querySelector('meta[name="apple-mobile-web-app-title"]');if(appleTitle)appleTitle.setAttribute('content',BRAND);const theme=document.querySelector('meta[name="theme-color"]');if(theme)theme.setAttribute('content','#07050d');let favicon=document.querySelector('link[rel="icon"]');if(!favicon){favicon=document.createElement('link');favicon.rel='icon';document.head.appendChild(favicon)}favicon.type='image/svg+xml';favicon.href=ICON;let touch=document.querySelector('link[rel="apple-touch-icon"]');if(!touch){touch=document.createElement('link');touch.rel='apple-touch-icon';document.head.appendChild(touch)}touch.href=ICON}
  function updateHeaderBrand(){const header=document.querySelector('header');if(!header)return;const image=header.querySelector('img');if(image){image.src=ICON;image.alt=BRAND;image.style.objectFit='contain';image.style.background='transparent'}const wordmark=header.querySelector('.prism-wordmark');if(wordmark)wordmark.textContent=BRAND}
  function updateMenuBrand(){const menu=document.getElementById('sideMenu');if(!menu)return;const image=menu.querySelector('.menu-brand img');if(image){image.src=ICON;image.alt=BRAND}const strong=menu.querySelector('.menu-brand strong');if(strong)strong.textContent=BRAND}
  function cleanNode(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const next=replaceBrand(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next}root.querySelectorAll?.('[aria-label],[title],[alt],[placeholder]').forEach(el=>{for(const attr of ['aria-label','title','alt','placeholder']){if(!el.hasAttribute(attr))continue;const current=el.getAttribute(attr),next=replaceBrand(current);if(next!==current)el.setAttribute(attr,next)}})}
  function addStyle(){if(document.getElementById('liftovaFinalPolish'))return;const style=document.createElement('style');style.id='liftovaFinalPolish';style.textContent=`
:root{--liftova-purple:#8c3cff;--liftova-bg:#07050d;--liftova-surface:#0e0c13;--liftova-border:#30243f;--liftova-text:#f8f5ff;--prism-blue:#8c3cff;--prism-accent:#8c3cff;--accent:#8c3cff!important}html{background:#07050d!important;-webkit-text-size-adjust:100%;touch-action:manipulation}html,body{color:#f8f5ff!important;-webkit-tap-highlight-color:transparent}body{background:#07050d!important;min-height:100dvh;-webkit-user-select:none;user-select:none}input,textarea,[contenteditable=true]{-webkit-user-select:text;user-select:text}
header{background:rgba(7,5,13,.96)!important;border-bottom:1px solid rgba(154,85,255,.22)!important;box-shadow:0 7px 22px rgba(0,0,0,.24)!important}.menu-toggle,.header-today{min-height:44px!important;min-width:44px!important;background:#121019!important;color:#fff!important;border:1px solid #30243f!important;border-radius:12px!important}.menu-toggle:active,.header-today:active{background:#1b1426!important;transform:scale(.96)}
#menuScrim{position:fixed!important;inset:0!important;z-index:1998!important;background:rgba(0,0,0,.76)!important;backdrop-filter:blur(4px)!important}#sideMenu{position:fixed!important;top:0!important;bottom:0!important;left:0!important;right:auto!important;width:min(86vw,340px)!important;max-width:340px!important;height:100dvh!important;z-index:1999!important;overflow-y:auto!important;overscroll-behavior:contain!important;background:radial-gradient(circle at 15% 0,rgba(133,54,255,.16),transparent 30%),linear-gradient(165deg,#100b18,#08070d 68%)!important;border-right:1px solid rgba(162,91,255,.28)!important;box-shadow:18px 0 52px rgba(0,0,0,.52)!important}#sideMenu:not(.open){transform:translateX(-105%)!important;pointer-events:none!important}#sideMenu.open{transform:translateX(0)!important;pointer-events:auto!important}#sideMenu .menu-head{padding-top:calc(14px + env(safe-area-inset-top))!important}
.prism-bottom-nav{position:fixed!important;left:0!important;right:0!important;bottom:0!important;z-index:1000!important;padding:5px max(8px,env(safe-area-inset-right)) calc(5px + env(safe-area-inset-bottom)) max(8px,env(safe-area-inset-left))!important;background:rgba(7,5,13,.94)!important;border-top:1px solid rgba(154,85,255,.22)!important;box-shadow:0 -8px 26px rgba(0,0,0,.32)!important;backdrop-filter:blur(20px)!important;-webkit-backdrop-filter:blur(20px)!important}.prism-bottom-nav button{min-height:50px!important;min-width:44px!important;color:#8e8798!important;background:transparent!important;border:0!important;border-radius:13px!important;font-size:9px!important;touch-action:manipulation;transition:background .12s ease,color .12s ease,transform .08s ease!important}.prism-bottom-nav button:active{transform:scale(.94)!important}.prism-bottom-nav button[aria-current=page]{color:#c897ff!important;background:rgba(125,43,245,.12)!important;box-shadow:inset 0 0 0 1px rgba(160,91,255,.1)!important}.container{padding-bottom:calc(86px + env(safe-area-inset-bottom))!important}.container>section:not(.hidden){animation:liftovaScreenIn .16s cubic-bezier(.2,.8,.2,1) both;will-change:opacity,transform}@keyframes liftovaScreenIn{from{opacity:.72;transform:translate3d(0,5px,0)}to{opacity:1;transform:none}}button,a,[role=button]{touch-action:manipulation;-webkit-touch-callout:none}button{font-family:inherit}.container button:not(.prism-bottom-nav button):not(.menu-toggle):not(.header-today){min-height:44px;box-shadow:none}.container button:active,.container a[role=button]:active{transform:scale(.975)}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:2px solid rgba(166,88,255,.55)!important;outline-offset:2px!important}.card{box-shadow:none}.back{display:inline-flex;align-items:center;min-height:44px;color:#bca2ff!important;font-size:11px!important;font-weight:760!important}.container input:not([type=checkbox]):not([type=radio]),.container select,.container textarea{min-height:44px;background:#100e16;color:#f8f5ff;border:1px solid #302740;border-radius:12px;box-shadow:none;font-size:16px}.container textarea{min-height:88px}.container input::placeholder,.container textarea::placeholder{color:#706a78;opacity:1}[role=dialog],dialog,.modal,.sheet,.prism-modal{background:#0e0c13!important;color:#f8f5ff!important;border-color:#352944!important;border-radius:20px!important;box-shadow:0 18px 55px rgba(0,0,0,.55)!important}.toast,.prism-toast,[role=status]{border-radius:12px!important;box-shadow:0 10px 30px rgba(0,0,0,.38)!important}.container a{color:#b98aff}.container h1,.container h2,.container h3{color:#fff}::selection{background:rgba(142,61,255,.38);color:#fff}html.prism-account-booting::after{content:'Restoring your MYLIFTCOACH account…'!important;background:#07050d url('images/liftova-splash.svg') center/cover no-repeat!important;color:transparent!important}
/* Legacy PRISM selectors remain for compatibility, but their visible treatment is MYLIFTCOACH purple. */
.prism-accent,.prism-primary,.prism-cta,.primary-btn,.btn-primary{border-color:#8c3cff!important}.prism-accent,.prism-primary{color:#c897ff!important}.prism-cta,.primary-btn,.btn-primary{background:#7d2bf5!important;color:#fff!important}.prism-logo,.prism-brand-logo{content:url('images/liftova-icon.svg?v=8')!important;object-fit:contain!important}
@media(display-mode:standalone){body{padding-top:0!important}header{padding-top:env(safe-area-inset-top)!important}.lh-hero{padding-top:calc(10px + env(safe-area-inset-top))!important}#sideMenu{padding-top:0!important}.container{min-height:100dvh}}
@media(max-width:430px){.container{padding-left:max(13px,env(safe-area-inset-left))!important;padding-right:max(13px,env(safe-area-inset-right))!important}.container>section:not(.hidden){max-width:100%;overflow-x:hidden}.container button{min-width:0}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
`;document.head.appendChild(style)}
  function run(){updateMetadata();addStyle();cleanNode();updateHeaderBrand();updateMenuBrand()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
  let screenObserver;function watchScreen(id){screenObserver?.disconnect();const screen=document.getElementById(id);if(!screen)return;screenObserver=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(node.nodeType===Node.TEXT_NODE)node.nodeValue=replaceBrand(node.nodeValue);else if(node.nodeType===Node.ELEMENT_NODE)cleanNode(node)}});screenObserver.observe(screen,{subtree:true,childList:true});requestAnimationFrame(()=>{cleanNode(screen);updateHeaderBrand();updateMenuBrand()})}
  const originalShowScreen=window.showScreen;if(typeof originalShowScreen==='function'&&!originalShowScreen.__liftovaBrand){const brandedShowScreen=function(id){const result=originalShowScreen.apply(this,arguments);watchScreen(id);requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));return result};brandedShowScreen.__liftovaBrand=true;window.showScreen=brandedShowScreen}
  const visibleScreen=[...document.querySelectorAll('.container > section[id],main > section[id]')].find(el=>!el.classList.contains('hidden'));if(visibleScreen)watchScreen(visibleScreen.id);document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateHeaderBrand();updateMenuBrand();cleanNode()}});
})();
