// MYLIFTCOACH Pro / Coach visual layer. Internal compatibility identifiers intentionally remain unchanged.
(() => {
  'use strict';
  const css=document.createElement('style');css.id='liftovaProStyles';css.textContent=`
    #prismProScreen{color:#f4fbff;background:radial-gradient(circle at 50% -10%,rgba(25,183,255,.18),transparent 34%),linear-gradient(180deg,#050b10 0%,#071018 55%,#03070b 100%);min-height:100dvh;margin:-20px -16px -36px;padding:calc(20px + env(safe-area-inset-top)) 16px calc(36px + env(safe-area-inset-bottom))}
    #prismProScreen .pro-back{border:1px solid rgba(25,183,255,.24)!important;background:rgba(7,15,22,.92)!important;color:#e9f8ff!important;border-radius:14px!important;min-height:44px;padding:0 14px!important;margin-bottom:14px}
    #prismProPageContent{max-width:760px;margin:auto}.liftova-pro-hero{position:relative;overflow:hidden;border:1px solid rgba(25,183,255,.36);border-radius:28px;padding:24px 22px;margin:2px 0 18px;background:linear-gradient(145deg,rgba(9,20,29,.98),rgba(5,11,17,.98));box-shadow:0 22px 70px rgba(0,0,0,.3)}
    .myliftcoach-pro-brand{display:flex;align-items:center;gap:12px;margin-bottom:15px}.myliftcoach-pro-logo{width:54px;height:54px;border-radius:14px;object-fit:contain;filter:drop-shadow(0 0 12px rgba(25,183,255,.28))}.myliftcoach-pro-wordmark{font-size:18px;font-weight:850;letter-spacing:.04em;color:#fff}.myliftcoach-pro-wordmark small{display:block;margin-top:3px;color:#19b7ff;font-size:10px;letter-spacing:.2em}
    .liftova-pro-hero h1{margin:0;font-size:34px;line-height:1.02;letter-spacing:-.035em;color:#fff}.liftova-pro-hero h1 span{display:block;color:#8bdcff}.liftova-pro-hero p{max-width:560px;margin:12px 0 0;color:#a9bbc5;font-size:15px;line-height:1.55}.liftova-pro-status{display:inline-flex;align-items:center;gap:7px;margin-top:17px;padding:8px 11px;border-radius:999px;background:rgba(25,183,255,.11);border:1px solid rgba(25,183,255,.27);color:#ccefff;font-size:11px;font-weight:750;letter-spacing:.05em}.liftova-pro-status i{width:7px;height:7px;border-radius:50%;background:#19b7ff}
    .liftova-intelligence-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:0 0 18px}.liftova-intelligence-card{min-height:138px;border-radius:20px;padding:16px;background:linear-gradient(150deg,rgba(10,22,31,.97),rgba(5,12,18,.97));border:1px solid rgba(25,183,255,.18);box-shadow:0 10px 32px rgba(0,0,0,.22)}.liftova-intelligence-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;margin-bottom:12px;background:#0a2635;border:1px solid rgba(25,183,255,.28);font-size:16px}.liftova-intelligence-card strong{display:block;color:#f4fbff;font-size:14px;margin-bottom:5px}.liftova-intelligence-card span{display:block;color:#96a9b4;font-size:12px;line-height:1.42}
    #prismProPageContent .card,#prismProPageContent .prism-pro-card,#prismProPageContent .pro-card{background:linear-gradient(150deg,#0c1922,#071018)!important;color:#f4fbff!important;border:1px solid rgba(25,183,255,.2)!important;box-shadow:0 12px 38px rgba(0,0,0,.24)!important;border-radius:20px!important}#prismProPageContent :is(h2,h3,strong){color:#f4fbff!important}#prismProPageContent :is(p,.small,small){color:#9fb2bd!important}#prismProPageContent :is(button,.prism-primary){border-radius:14px!important}#prismProPageContent .prism-primary,#prismProPageContent button.primary{background:#087fbd!important;border-color:#19b7ff!important;color:white!important}#prismProPageContent .prism-pro-badge{background:rgba(25,183,255,.11)!important;color:#ccefff!important;border:1px solid rgba(25,183,255,.28)!important}
    @media(max-width:430px){.liftova-pro-hero h1{font-size:30px}.liftova-intelligence-grid{grid-template-columns:1fr 1fr}.liftova-intelligence-card{min-height:148px;padding:14px}}
  `;document.head.appendChild(css);
  const intro=()=>`<div class="liftova-pro-hero" id="liftovaProHero"><div class="myliftcoach-pro-brand"><img class="myliftcoach-pro-logo" src="images/liftova-icon.svg?v=10" alt="MYLIFTCOACH"><div class="myliftcoach-pro-wordmark">MYLIFTCOACH · PRO</div></div><h1>Your training.<span>Now it adapts to you.</span></h1><p>Free gives you a premium workout experience. Pro adds the intelligence layer — learning from what you log and helping decide what should change next.</p><div class="liftova-pro-status"><i></i> ADAPTIVE INTELLIGENCE</div></div><div class="liftova-intelligence-grid" id="liftovaIntelligenceGrid"><div class="liftova-intelligence-card"><div class="liftova-intelligence-icon">↗</div><strong>Smart Progression</strong><span>Uses your recent performance to guide the next weight and rep target.</span></div><div class="liftova-intelligence-card"><div class="liftova-intelligence-icon">◈</div><strong>Recovery Awareness</strong><span>Factors in readiness and recent training before pushing progression.</span></div><div class="liftova-intelligence-card"><div class="liftova-intelligence-icon">⌁</div><strong>Plateau Detection</strong><span>Surfaces stalled patterns so training can change before progress goes flat.</span></div><div class="liftova-intelligence-card"><div class="liftova-intelligence-icon">◎</div><strong>Deeper Analytics</strong><span>Turns logged workouts into longer-term strength, volume and consistency signals.</span></div></div>`;
  function rebrandProContent(){const screen=document.getElementById('prismProScreen'),content=document.getElementById('prismProPageContent');if(!screen||!content)return;if(!document.getElementById('liftovaProHero')){const wrapper=document.createElement('div');wrapper.innerHTML=intro();while(wrapper.firstChild)content.insertBefore(wrapper.firstChild,content.firstChild);}const walker=document.createTreeWalker(content,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(node.parentElement?.closest('#liftovaProHero,#liftovaIntelligenceGrid'))continue;if(/PRISM|LIFTOVA/.test(node.nodeValue||''))node.nodeValue=node.nodeValue.replaceAll('PRISM','MYLIFTCOACH').replaceAll('LIFTOVA','MYLIFTCOACH');}screen.setAttribute('aria-label','MYLIFTCOACH Pro');}
  const observer=new MutationObserver(rebrandProContent);const boot=()=>{const content=document.getElementById('prismProPageContent');if(!content)return setTimeout(boot,120);observer.observe(content,{childList:true,subtree:true});rebrandProContent();};boot();
})();
