// Canonical LIFTOVA Home dashboard. Keeps existing workout/data engines intact.
(() => {
  'use strict';
  const addStyles=()=>{if(document.querySelector('link[data-liftova-home]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='liftova-home.css?v=7';l.dataset.liftovaHome='true';document.head.appendChild(l)};
  const safeJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const today=()=>new Date();
  function legacySnapshot(home){const text=(home?.innerText||'').replace(/\s+/g,' ').trim();const workoutHeading=[...(home?.querySelectorAll('h2,h3,strong')||[])].map(e=>(e.textContent||'').trim()).find(v=>/day\s*\d|upper body|lower body|push|pull|legs|full body/i.test(v))||'Your Next Workout';const detail=text.match(/\d+\s+exercises?\s*[·•-]\s*(?:about\s*)?\d+\s*min/i)?.[0]||'';const greeting=[...(home?.querySelectorAll('h1,h2,h3')||[])].map(e=>(e.textContent||'').trim()).find(v=>/good (morning|afternoon|evening)|ready to train/i.test(v))||'';return{workoutHeading,detail,greeting}}
  const profileName=legacy=>{const n=legacy.greeting.replace(/^(good (morning|afternoon|evening)|ready to train)[,\s]*/i,'').replace(/[?!]+$/,'').trim();if(n)return n;for(const k of['prismLocalProfileV1','prismProfileV1']){const p=safeJson(k,{});const x=String(p?.displayName||p?.name||'').trim();if(x)return x}return''};
  const history=()=>{for(const k of['workoutHistoryV52','workoutHistory']){const v=safeJson(k,null);if(Array.isArray(v))return v}return[]};
  const weekStart=()=>{const n=today(),s=new Date(n);s.setHours(0,0,0,0);s.setDate(n.getDate()-((n.getDay()+6)%7));return s};
  const workoutCountThisWeek=()=>{const s=weekStart(),n=today();return history().filter(i=>{const r=i?.date||i?.completedAt||i?.day||i?.timestamp,d=r?new Date(r):null;return d&&Number.isFinite(d.getTime())&&d>=s&&d<=n}).length};
  const completedSetCountThisWeek=()=>{const s=weekStart(),n=today();let sets=0;for(const session of history()){const r=session?.date||session?.completedAt||session?.day||session?.timestamp,d=r?new Date(r):null;if(!d||!Number.isFinite(d.getTime())||d<s||d>n)continue;for(const ex of session?.exercises||[])sets+=(ex?.sets||[]).filter(x=>Number(x?.reps)>0).length}return sets};
  const streak=()=>{const days=new Set(history().map(i=>{const r=i?.date||i?.completedAt||i?.day||i?.timestamp,d=r?new Date(r):null;return d&&Number.isFinite(d.getTime())?`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`:null}).filter(Boolean));if(!days.size)return 0;let c=0;const d=today();d.setHours(12,0,0,0);for(let i=0;i<366;i++){const k=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;if(!days.has(k)){if(i===0){d.setDate(d.getDate()-1);continue}break}c++;d.setDate(d.getDate()-1)}return c};
  const activeWorkout=()=>{for(const k of['prismActiveWorkoutV1','activeWorkout']){const v=safeJson(k,null);if(v)return v}return null};
  const planDays=()=>{for(const k of['workoutGoalsV1','prismWorkoutGoalsV1']){const g=safeJson(k,{}),d=Number(g?.days||g?.trainingDays);if(Number.isFinite(d)&&d>0)return d}return 4};
  const weekMarkup=()=>{const n=today(),m=new Date(n);m.setDate(n.getDate()-((n.getDay()+6)%7));return Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);const a=d.toDateString()===n.toDateString(),label=['MON','TUE','WED','THU','FRI','SAT','SUN'][i];return `<div class="lh-day ${a?'active':''}"><strong>${label}</strong><span>${d.getDate()}</span></div>`}).join('')};
  const clickExisting=patterns=>{const buttons=[...document.querySelectorAll('button,a')].filter(e=>!e.closest('.liftova-home-shell'));const t=buttons.find(e=>patterns.some(rx=>rx.test((e.textContent||'').trim())));if(t){t.click();return true}return false};
  function wire(shell){shell.querySelector('[data-lh="workouts"]')?.addEventListener('click',()=>clickExisting([/^workouts$/i,/my workouts/i]));shell.querySelector('[data-lh="progress"]')?.addEventListener('click',()=>clickExisting([/^progress$/i,/overall progress/i]));shell.querySelector('[data-lh="library"]')?.addEventListener('click',()=>clickExisting([/exercise library/i,/^library$/i]))}
  function render(){const home=document.getElementById('home');if(!home)return;addStyles();const legacy=legacySnapshot(home),name=profileName(legacy),resume=!!activeWorkout(),days=planDays(),workouts=workoutCountThisWeek(),sets=completedSetCountThisWeek(),current=home.querySelector('.liftova-home-shell'),shell=current||document.createElement('div');shell.className='liftova-home-shell';shell.innerHTML=`
    <section class="lh-hero"><div class="lh-hero-brand"><img src="images/liftova-icon.svg" alt="LIFTOVA"><div><strong>LIFTOVA</strong><span>TRAIN · TRACK · PROGRESS</span></div></div>${name?`<div class="lh-welcome">Welcome back,<br><strong>${name}</strong></div>`:''}</section>
    <div class="lh-week">${weekMarkup()}</div>
    <section class="lh-workout"><div class="lh-label">${resume?'WORKOUT IN PROGRESS':'TODAY’S WORKOUT'}</div><h2>${resume?'RESUME WORKOUT':legacy.workoutHeading.toUpperCase()}</h2><p>${legacy.detail||`${days} day training plan`}</p><div class="lh-meta"><span>◷ 45–60 min</span><span>▥ ${days} days/week</span><span>◎ Hypertrophy</span></div><div class="lh-overview"><b>WORKOUT OVERVIEW</b><span>Open the Workout tab below when you’re ready to train.</span></div></section>
    <div class="lh-summary"><section class="lh-stat"><span>THIS WEEK</span><strong>${workouts}/${days}</strong><small>workouts</small></section><section class="lh-stat"><span>TOTAL SETS</span><strong>${sets}</strong><small>completed</small></section><section class="lh-stat"><span>STREAK</span><strong>${streak()}</strong><small>days</small></section></div>
    <section class="lh-coach-strip"><div class="lh-coach-icon">◆</div><div class="lh-coach-copy"><b>LIFTOVA COACH</b><p>${workouts?'Keep building on this week’s work.':'Log your first workout and LIFTOVA will start learning from your training.'}</p></div></section>
    <div class="lh-actions"><button data-lh="library"><span>✚</span><b>LIBRARY</b></button><button data-lh="workouts"><span>▣</span><b>MY PLAN</b></button><button data-lh="progress"><span>▥</span><b>PROGRESS</b></button></div>`;if(!current)home.prepend(shell);document.body.classList.add('liftova-ui');home.classList.add('liftova-home');wire(shell)}
  function boot(){render();const originalGoHome=window.goHome;if(typeof originalGoHome==='function'&&!originalGoHome.__liftovaWrapped){const wrapped=function(...args){const result=originalGoHome.apply(this,args);requestAnimationFrame(render);return result};wrapped.__liftovaWrapped=true;window.goHome=wrapped}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
