// MYLIFTCOACH Pro / Coach visual layer. Internal compatibility identifiers intentionally remain unchanged.
(() => {
  'use strict';
  const BRAND='MYLIFTCOACH';
  const ICON='images/liftova-icon.svg?v=10';
  const css=document.createElement('style');css.id='myliftcoachProStyles';css.textContent=`
    #prismProScreen{color:#f8f5ff;background:radial-gradient(circle at 50% -10%,rgba(128,54,255,.20),transparent 35%),linear-gradient(180deg,#09050f 0%,#08060d 55%,#030205 100%);min-height:100dvh;margin:-20px -16px -36px;padding:calc(20px + env(safe-area-inset-top)) 16px calc(36px + env(safe-area-inset-bottom))}
    #prismProScreen .pro-back{border:1px solid rgba(155,91,255,.30)!important;background:rgba(10,6,16,.94)!important;color:#f8f5ff!important;border-radius:14px!important;min-height:44px;padding:0 14px!important;margin-bottom:14px}
    #prismProPageContent{max-width:760px;margin:auto}.myliftcoach-pro-hero{position:relative;overflow:hidden;border:1px solid rgba(151,79,255,.38);border-radius:28px;padding:24px 22px;margin:2px 0 18px;background:linear-gradient(145deg,rgba(19,10,31,.98),rgba(7,4,12,.99));box-shadow:0 22px 70px rgba(0,0,0,.42)}
    .myliftcoach-pro-brand{display:flex;align-items:center;gap:12px;margin-bottom:15px}.myliftcoach-pro-mark{width:58px;height:58px;display:block;object-fit:contain;border-radius:15px;background:#09050f;border:1px solid rgba(161,97,255,.42);box-shadow:0 0 24px rgba(127,54,255,.20)}.myliftcoach-pro-wordmark{font-size:18px;font-weight:850;letter-spacing:.04em;color:#fff}
    .myliftcoach-pro-hero h1{margin:0;font-size:34px;line-height:1.02;letter-spacing:-.035em;color:#fff}.myliftcoach-pro-hero h1 span{display:block;color:#c5a3ff}.myliftcoach-pro-hero p{max-width:560px;margin:12px 0 0;color:#aaa3b5;font-size:15px;line-height:1.55}.myliftcoach-pro-status{display:inline-flex;align-items:center;gap:7px;margin-top:17px;padding:8px 11px;border-radius:999px;background:rgba(135,65,255,.12);border:1px solid rgba(156,91,255,.30);color:#dccbff;font-size:11px;font-weight:750;letter-spacing:.05em}.myliftcoach-pro-status i{width:7px;height:7px;border-radius:50%;background:#a568ff}
    .myliftcoach-intelligence-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:0 0 18px}.myliftcoach-intelligence-card{min-height:138px;border-radius:20px;padding:16px;background:linear-gradient(150deg,rgba(18,10,29,.98),rgba(7,4,12,.99));border:1px solid rgba(150,82,255,.22);box-shadow:0 10px 32px rgba(0,0,0,.30)}.myliftcoach-intelligence-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;margin-bottom:12px;background:#1b0d2d;border:1px solid rgba(158,94,255,.34);color:#d4bcff;font-size:16px}.myliftcoach-intelligence-card strong{display:block;color:#f8f5ff;font-size:14px;margin-bottom:5px}.myliftcoach-intelligence-card span{display:block;color:#aaa3b5;font-size:12px;line-height:1.42}
    #prismProPageContent .card,#prismProPageContent .prism-pro-card,#prismProPageContent .pro-card{background:linear-gradient(150deg,#130a1f,#08050d)!important;color:#f8f5ff!important;border:1px solid rgba(151,82,255,.24)!important;box-shadow:0 12px 38px rgba(0,0,0,.32)!important;border-radius:20px!important}#prismProPageContent :is(h2,h3,strong){color:#f8f5ff!important}#prismProPageContent :is(p,.small,small){color:#aaa3b5!important}#prismProPageContent :is(button,.prism-primary){border-radius:14px!important}#prismProPageContent .prism-primary,#prismProPageContent button.primary{background:#6d35c5!important;border-color:#9b63f0!important;color:white!important}#prismProPageContent .prism-pro-badge{background:rgba(135,65,255,.12)!important;color:#dccbff!important;border:1px solid rgba(156,91,255,.30)!important}
    @media(max-width:430px){.myliftcoach-pro-hero h1{font-size:30px}.myliftcoach-intelligence-grid{grid-template-columns:1fr 1fr}.myliftcoach-intelligence-card{min-height:148px;padding:14px}}
  `;document.head.appendChild(css);
  const intro=()=>`<div class="myliftcoach-pro-hero" id="myliftcoachProHero"><div class="myliftcoach-pro-brand"><img class="myliftcoach-pro-mark" src="${ICON}" alt="MYLIFTCOACH logo"><div class="myliftcoach-pro-wordmark">MYLIFTCOACH · PRO</div></div><h1>Your training.<span>Now it adapts to you.</span></h1><p>Free gives you a premium workout experience. Pro adds the intelligence layer — learning from what you log and helping decide what should change next.</p><div class="myliftcoach-pro-status"><i></i> ADAPTIVE INTELLIGENCE</div></div><div class="myliftcoach-intelligence-grid" id="myliftcoachIntelligenceGrid"><div class="myliftcoach-intelligence-card"><div class="myliftcoach-intelligence-icon">↗</div><strong>Smart Progression</strong><span>Uses your recent performance to guide the next weight and rep target.</span></div><div class="myliftcoach-intelligence-card"><div class="myliftcoach-intelligence-icon">◈</div><strong>Recovery Awareness</strong><span>Factors in readiness and recent training before pushing progression.</span></div><div class="myliftcoach-intelligence-card"><div class="myliftcoach-intelligence-icon">⌁</div><strong>Plateau Detection</strong><span>Surfaces stalled patterns so training can change before progress goes flat.</span></div><div class="myliftcoach-intelligence-card"><div class="myliftcoach-intelligence-icon">◎</div><strong>Deeper Analytics</strong><span>Turns logged workouts into longer-term strength, volume and consistency signals.</span></div></div>`;
  function scrubLegacyPro(content){
    const walker=document.createTreeWalker(content,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue)n.nodeValue=n.nodeValue.replace(/PRISM/gi,BRAND).replace(/LIFTOVA/gi,BRAND)});
    content.querySelectorAll('img').forEach(img=>{if(!img.closest('.myliftcoach-pro-brand')){const hay=`${img.src} ${img.alt} ${img.className}`;if(/prism|liftova/i.test(hay)){img.src=ICON;img.alt='MYLIFTCOACH logo';}}});
  }
  function applyProPresentation(){const screen=document.getElementById('prismProScreen'),content=document.getElementById('prismProPageContent');if(!screen||!content)return;if(!document.getElementById('myliftcoachProHero')){const wrapper=document.createElement('div');wrapper.innerHTML=intro();while(wrapper.firstChild)content.insertBefore(wrapper.firstChild,content.firstChild);}scrubLegacyPro(content);screen.setAttribute('aria-label','MYLIFTCOACH Pro');}
  const observer=new MutationObserver(applyProPresentation);const boot=()=>{const content=document.getElementById('prismProPageContent');if(!content)return setTimeout(boot,120);observer.observe(content,{childList:true,subtree:true});applyProPresentation();};boot();
})();
