// Canonical LIFTOVA Home dashboard. Presentation only; existing workout/data engines stay intact.
(() => {
'use strict';
const addStyles=()=>{if(document.querySelector('link[data-liftova-home]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='liftova-home.css?v=8';l.dataset.liftovaHome='true';document.head.appendChild(l)};
const safeJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const today=()=>new Date();
function legacySnapshot(home){const text=(home?.innerText||'').replace(/\s+/g,' ').trim();const workoutHeading=[...(home?.querySelectorAll('h2,h3,strong')||[])].map(e=>(e.textContent||'').trim()).find(v=>/day\s*\d|upper body|lower body|push|pull|legs|full body/i.test(v))||'Upper Body';const detail=text.match(/\d+\s+exercises?\s*[·•-]\s*(?:about\s*)?\d+\s*min/i)?.[0]||'';return{workoutHeading,detail}}
const history=()=>{for(const k of['workoutHistoryV52','workoutHistory']){const v=safeJson(k,null);if(Array.isArray(v))return v}return[]};
const weekStart=()=>{const n=today(),s=new Date(n);s.setHours(0,0,0,0);s.setDate(n.getDate()-((n.getDay()+6)%7));return s};
const workoutCountThisWeek=()=>{const s=weekStart(),n=today();return history().filter(i=>{const r=i?.date||i?.completedAt||i?.day||i?.timestamp,d=r?new Date(r):null;return d&&Number.isFinite(d.getTime())&&d>=s&&d<=n}).length};
const streak=()=>{const days=new Set(history().map(i=>{const r=i?.date||i?.completedAt||i?.day||i?.timestamp,d=r?new Date(r):null;return d&&Number.isFinite(d.getTime())?`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`:null}).filter(Boolean));if(!days.size)return 0;let c=0;const d=today();d.setHours(12,0,0,0);for(let i=0;i<366;i++){const k=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;if(!days.has(k)){if(i===0){d.setDate(d.getDate()-1);continue}break}c++;d.setDate(d.getDate()-1)}return c};
const planDays=()=>{for(const k of['workoutGoalsV1','prismWorkoutGoalsV1']){const g=safeJson(k,{}),d=Number(g?.days||g?.trainingDays);if(Number.isFinite(d)&&d>0)return d}return 4};
function actualToday(home){const candidates=[];const add=(name,root)=>{if(!root||root.closest?.('.liftova-home-shell'))return;const exercises=[...root.querySelectorAll?.('.exercise,.builder-exercise,[data-exercise-id],.workout-exercise')||[]];if(!exercises.length)return;const rows=exercises.map(el=>{const title=(el.querySelector('.exercise-title,.library-name,strong,h3,h4')?.textContent||el.dataset?.exerciseName||'').trim();const muscle=(el.querySelector('.muscle,.badge,[data-muscle]')?.textContent||el.dataset?.muscle||'').trim();return{title,muscle}}).filter(x=>x.title);if(rows.length)candidates.push({name,rows})};[...home.children].forEach(el=>{if(el.classList?.contains('liftova-home-shell'))return;const name=(el.querySelector?.('h2,h3,.workout-title,.day-title')?.textContent||'').trim();add(name,el)});return candidates[0]||null}
function workoutSnapshot(home){const actual=actualToday(home),legacy=legacySnapshot(home);if(actual){const muscles=actual.rows.map(x=>x.muscle).filter(Boolean);const groups={};muscles.forEach(m=>m.split(/[·,\/]/).map(s=>s.trim()).filter(Boolean).forEach(s=>groups[s]=(groups[s]||0)+1));return{name:actual.name||legacy.workoutHeading,exercises:actual.rows.length,muscles:[...new Set(muscles)].slice(0,4).join(' · '),overview:Object.entries(groups).slice(0,5),custom:true}}const detail=legacy.detail.match(/(\d+)\s+exercises?.*?(\d+)\s*min/i);return{name:legacy.workoutHeading,exercises:Number(detail?.[1])||0,minutes:Number(detail?.[2])||0,muscles:'',overview:[],custom:false}}
const weekLabels=['Upper','Lower','Rest','Upper','Lower','Rest','Rest'];const weekIcons=['⌁','♙','⌁','◎','♙','⌁','◎'];
const weekMarkup=()=>{const n=today();return ['MON','TUE','WED','THU','FRI','SAT','SUN'].map((label,i)=>{const dayIndex=(n.getDay()+6)%7,a=i===dayIndex;return `<div class="lh-day ${a?'active':''}"><strong>${label}</strong><b>${weekIcons[i]}</b><span>${weekLabels[i]}</span></div>`}).join('')};
const workoutMuscles=name=>/lower|leg/i.test(name)?'Quads · Hamstrings · Glutes · Calves':/push/i.test(name)?'Chest · Shoulders · Triceps':/pull/i.test(name)?'Back · Biceps · Rear Delts':'Chest · Back · Shoulders · Arms';
const chartBars=()=>[46,18,30,64,40,14,28].map((h,i)=>`<i style="height:${h}%"><span>${['M','T','W','T','F','S','S'][i]}</span></i>`).join('');
function render(){const home=document.getElementById('home');if(!home)return;addStyles();const data=workoutSnapshot(home),days=planDays(),workouts=workoutCountThisWeek(),name=String(data.name||'Today’s Workout').toUpperCase(),muscles=data.muscles||workoutMuscles(name),count=data.exercises||0,minutes=data.minutes||Math.max(30,count*6),overview=data.overview.length?data.overview.map(([m,n])=>`<li>${esc(m)}: ${n} exercise${n===1?'':'s'}</li>`).join(''):`<li>${esc(muscles)}</li>`,current=home.querySelector('.liftova-home-shell'),shell=current||document.createElement('div');shell.className = 'liftova-home-shell';shell.innerHTML=`<section class="lh-hero"><div class="lh-hero-mark"><img src="images/liftova-icon.svg" alt="LIFTOVA"></div><strong>LIFTOVA</strong><span>TRAIN <i>•</i> TRACK <i>•</i> PROGRESS</span></section><div class="lh-week">${weekMarkup()}</div><section class="lh-workout"><div class="lh-label">TODAY’S WORKOUT</div><h2>${esc(name)}</h2><p>${esc(muscles)}</p><div class="lh-meta"><span><b>◴</b>${minutes} min<small>EST. TIME</small></span><span><b>▥</b>${count||'—'} exercises<small>TOTAL</small></span><span><b>◎</b>${data.custom?'Custom':'Scheduled'}<small>WORKOUT</small></span></div><div class="lh-overview"><strong>WORKOUT OVERVIEW</strong><ul>${overview}</ul></div></section><div class="lh-insights"><section class="lh-progress"><header><b>↗</b><strong>WEEKLY PROGRESS</strong><span>›</span></header><div class="lh-chart">${chartBars()}</div></section><section class="lh-streak"><header><b>🔥</b><strong>WORKOUT STREAK</strong><span>›</span></header><div class="lh-streak-body"><div><strong>${streak()}</strong><small>DAYS</small></div><div class="lh-ring" style="--pct:${Math.min(100,(workouts/Math.max(days,1))*100)}%"></div></div></section></div>`;if(!current)home.prepend(shell);document.body.classList.add('liftova-ui');home.classList.add('liftova-home')}
function loadProfileBranding(){if(document.querySelector('script[data-liftova-profile-branding]'))return;const s=document.createElement('script');s.src='liftova-profile-branding.js?v=1';s.dataset.liftovaProfileBranding='true';document.body.appendChild(s)}
function boot(){render();loadProfileBranding();const originalGoHome=window.goHome;if(typeof originalGoHome==='function'&&!originalGoHome.__liftovaWrapped){const wrapped=function(...args){const result=originalGoHome.apply(this,args);requestAnimationFrame(render);return result};wrapped.__liftovaWrapped=true;window.goHome=wrapped}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
