/* PRISM Pro Advanced Measurements beta. Local-only dated body measurements. */
const PRISM_MEASURE_KEY='prismMeasurementsV1';
const PRISM_MEASURE_FIELDS=[['weight','Weight','lb'],['waist','Waist','in'],['chest','Chest','in'],['hips','Hips','in'],['arm','Arm','in'],['thigh','Thigh','in'],['bodyFat','Body fat','%']];
function prismMeasurementRead(){try{const v=JSON.parse(localStorage.getItem(PRISM_MEASURE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function prismMeasurementWrite(rows){localStorage.setItem(PRISM_MEASURE_KEY,JSON.stringify(rows));}
function prismMeasurementPhase(date){if(typeof prismPhaseRead!=='function')return null;const d=new Date(`${date}T12:00:00`);return prismPhaseRead().find(p=>d>=new Date(`${p.startDate}T00:00:00`)&&d<=new Date(`${p.endDate||'2999-12-31'}T23:59:59`))||null;}
function prismMeasurementId(){return `measure-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function prismMeasurementSave(values){if(!values?.date)return false;const row={id:values.id||prismMeasurementId(),date:values.date,phaseId:prismMeasurementPhase(values.date)?.id||null,createdAt:new Date().toISOString()};let has=false;for(const [key] of PRISM_MEASURE_FIELDS){const n=Number(values[key]);row[key]=Number.isFinite(n)&&n>0?n:null;if(row[key]!=null)has=true;}if(!has)return false;const rows=prismMeasurementRead(),i=rows.findIndex(x=>x.id===row.id);if(i>=0)rows[i]=row;else rows.push(row);rows.sort((a,b)=>String(b.date).localeCompare(String(a.date)));prismMeasurementWrite(rows);return row;}
function prismMeasurementDelete(id){prismMeasurementWrite(prismMeasurementRead().filter(x=>x.id!==id));}
function prismMeasurementNearest(date,maxDays=7){const target=new Date(`${date}T12:00:00`).getTime();let best=null,bestGap=Infinity;for(const row of prismMeasurementRead()){const t=new Date(`${row.date}T12:00:00`).getTime(),gap=Math.abs(t-target)/86400000;if(Number.isFinite(t)&&gap<bestGap&&gap<=maxDays){best=row;bestGap=gap;}}return best;}
function prismMeasurementCompare(beforeDate,afterDate){const before=prismMeasurementNearest(beforeDate),after=prismMeasurementNearest(afterDate);if(!before||!after)return {before,after,changes:[]};const changes=PRISM_MEASURE_FIELDS.map(([key,label,unit])=>{const a=Number(before[key]),b=Number(after[key]);return a>0&&b>0?{key,label,unit,before:a,after:b,delta:b-a}:null;}).filter(Boolean);return {before,after,changes};}
function prismMeasurementFormat(n,unit){const sign=n>0?'+':'';return `${sign}${n.toFixed(1)} ${unit}`;}
function prismMeasurementComparisonHTML(beforeDate,afterDate){const c=prismMeasurementCompare(beforeDate,afterDate);if(!c.before||!c.after)return `<p class="small">Add measurements on or near both photo dates to show body changes with this comparison.</p>`;if(!c.changes.length)return `<p class="small">No matching measurements are available between these dates.</p>`;return `<div class="prism-measure-compare"><p class="small">Measurements: ${escapeHTML(c.before.date)} → ${escapeHTML(c.after.date)}</p>${c.changes.map(x=>`<div class="journey-summary"><span>${escapeHTML(x.label)}: ${x.before.toFixed(1)} → ${x.after.toFixed(1)} ${escapeHTML(x.unit)}</span><strong>${escapeHTML(prismMeasurementFormat(x.delta,x.unit))}</strong></div>`).join('')}</div>`;}
function prismMeasurementPhaseLabel(id){if(!id||typeof prismPhaseRead!=='function')return '';const p=prismPhaseRead().find(x=>x.id===id);return p?((window.PRISM_GOAL_NAMES||{})[p.type]||p.type):'';}
function prismMeasurementFormHTML(){const today=new Date().toISOString().slice(0,10);return `<div class="card"><span class="journey-eyebrow">PRISM PRO · MEASUREMENTS</span><h3>Body Measurements</h3><p class="small">Save measurements over time and compare them with goal phases and progress photos. Entries stay on this device.</p><form onsubmit="prismMeasurementHandleSave(event)"><label>Date<input name="date" type="date" value="${today}" max="${today}" required></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${PRISM_MEASURE_FIELDS.map(([key,label,unit])=>`<label>${escapeHTML(label)} (${escapeHTML(unit)})<input name="${key}" type="number" min="0" step="0.1" inputmode="decimal" placeholder="Optional"></label>`).join('')}</div><button type="submit">Save Measurements</button><output id="prismMeasurementStatus" role="status"></output></form></div>`;}
function prismMeasurementHistoryHTML(){const rows=prismMeasurementRead();if(!rows.length)return `<div class="card"><p class="small">No measurement history yet.</p></div>`;return `<div class="card"><h3>Measurement history</h3>${rows.slice(0,20).map(r=>{const vals=PRISM_MEASURE_FIELDS.filter(([k])=>Number(r[k])>0).map(([k,l,u])=>`${l}: ${Number(r[k]).toFixed(1)} ${u}`).join(' · '),phase=prismMeasurementPhaseLabel(r.phaseId);return `<div class="prism-volume-row"><span><strong>${escapeHTML(r.date)}</strong>${phase?` · ${escapeHTML(phase)}`:''}</span><p class="small">${escapeHTML(vals)}</p><button type="button" class="secondary" onclick="prismMeasurementRemove('${escapeHTML(r.id)}')">Delete</button></div>`}).join('')}</div>`;}
function prismMeasurementRender(){const host=document.getElementById('prismMeasurements');if(!host)return;if(typeof canAccessFeature==='function'&&!canAccessFeature('advanced_measurement_trends')){host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO ✦</span><h3>Advanced Measurements</h3><p class="small">Track dated body measurements and compare changes across goal phases and progress photos.</p><button type="button" onclick="showProPreview('advanced_measurement_trends')">Preview measurements</button></div>`;return;}host.innerHTML=prismMeasurementFormHTML()+prismMeasurementHistoryHTML();}
function prismMeasurementHandleSave(event){event.preventDefault();const f=event.currentTarget,values={date:f.date.value};for(const [key] of PRISM_MEASURE_FIELDS)values[key]=f[key].value;const saved=prismMeasurementSave(values),status=document.getElementById('prismMeasurementStatus');if(!saved){if(status)status.textContent='Enter at least one measurement.';return;}f.reset();f.date.value=new Date().toISOString().slice(0,10);prismMeasurementRender();}
function prismMeasurementRemove(id){if(!confirm('Delete this measurement entry?'))return;prismMeasurementDelete(id);prismMeasurementRender();}
function prismMeasurementMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismMeasurements');if(!host){host=document.createElement('div');host.id='prismMeasurements';const photos=document.getElementById('prismProgressPhotos');if(photos)photos.insertAdjacentElement('afterend',host);else screen.appendChild(host);}prismMeasurementRender();}
window.PRISM_MEASURE_FIELDS=PRISM_MEASURE_FIELDS;window.prismMeasurementRead=prismMeasurementRead;window.prismMeasurementSave=prismMeasurementSave;window.prismMeasurementDelete=prismMeasurementDelete;window.prismMeasurementNearest=prismMeasurementNearest;window.prismMeasurementCompare=prismMeasurementCompare;window.prismMeasurementComparisonHTML=prismMeasurementComparisonHTML;window.prismMeasurementRender=prismMeasurementRender;window.prismMeasurementMount=prismMeasurementMount;window.prismMeasurementHandleSave=prismMeasurementHandleSave;window.prismMeasurementRemove=prismMeasurementRemove;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismMeasurements){const original=showOverallProgress;showOverallProgress=function(){original();prismMeasurementMount();};showOverallProgress.__prismMeasurements=true;}