/* PRISM Pre-Workout Plan v1.1 — exercise targets adapt to today's readiness. */
const PRISM_PREWORKOUT_VERSION='1.1';
function prismPreSafe(fn,fallback=null){try{const v=fn();return v==null?fallback:v}catch{return fallback}}
function prismPreWorkoutExerciseIds(){const ids=typeof activeWorkoutExerciseIds!=='undefined'&&Array.isArray(activeWorkoutExerciseIds)?activeWorkoutExerciseIds:[];return ids.filter(Boolean);}
function prismPreRoundLoad(value){return Math.max(0,Math.round(Number(value||0)/5)*5)}
function prismPreWorkoutTarget(id){const ex=prismPreSafe(()=>getExercise(id),null);if(!ex)return null;const progression=prismPreSafe(()=>progressionSuggestion(id),null),fatigue=prismPreSafe(()=>prismAdaptiveFatigueSignals(),null),fatigueRow=fatigue?.repeated?.find(x=>x.id===id),accepted=prismPreSafe(()=>prismAdaptiveAccepted(),[])||[],adjustment=accepted.find(p=>p?.meta?.exerciseId===id||p?.id===`fatigue-${id}`),readiness=prismPreSafe(()=>typeof prismReadinessAnalyze==='function'?prismReadinessAnalyze():null,null);let weight=Number(progression?.weight||progression?.lastWeight||0),min=Number(progression?.range?.min||8),max=Number(progression?.range?.max||12),mode=progression?.status==='ready'?'BUILD':'NORMAL',reason=progression?.status==='ready'?'Your saved performance supports a progression attempt.':'Use your recent working load and improve reps or execution before forcing an increase.';
if(fatigueRow||adjustment){mode='CONTROL';weight=Number(progression?.lastWeight||weight||0);max=Math.max(min,Math.min(max,Number(progression?.lastReps?.[0]||max)));reason=adjustment?.why||`PRISM has ${fatigueRow.count} recent fatigue signals for this exercise, so progression pressure is reduced.`;}
if(readiness?.mode==='CONTROL'&&!['RECOVERY','CONTROL'].includes(mode)){mode='CONTROL';weight=Number(progression?.lastWeight||weight||0);max=Math.max(min,max-1);reason=`Today's readiness is ${readiness.score}/5. ${readiness.guidance}`;}
if(readiness?.mode==='RECOVERY'){mode='RECOVERY';const base=Number(progression?.lastWeight||weight||0);weight=base>0?prismPreRoundLoad(base*.95):0;min=Math.max(6,min-1);max=Math.max(min,max-2);reason=`Today's readiness is ${readiness.score}/5. ${readiness.guidance}`;}
if(readiness?.mode==='BUILD'&&mode==='NORMAL'&&progression?.status==='ready'){mode='BUILD';reason=`Today's readiness is ${readiness.score}/5 and your saved performance supports progression.`;}
return {id,name:ex.name||id,weight,min,max,mode,reason,readinessMode:readiness?.mode||null};}
function prismPreWorkoutPlan(){const ids=prismPreWorkoutExerciseIds(),readiness=prismPreSafe(()=>typeof prismReadinessAnalyze==='function'?prismReadinessAnalyze():null,null),targets=ids.map(prismPreWorkoutTarget).filter(Boolean),next=prismPreSafe(()=>prismNextSessionPlan(),null);return {version:PRISM_PREWORKOUT_VERSION,generatedAt:new Date().toISOString(),readiness,targets,next,ready:targets.length>0};}
function prismPreWorkoutRender(){const host=document.getElementById('prismPreWorkoutPlan');if(!host)return;const plan=prismPreWorkoutPlan();if(!plan.ready){host.innerHTML='';host.classList.add('hidden');return;}host.classList.remove('hidden');host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO · PRE-WORKOUT PLAN</span><h3>Today's exercise targets</h3>${plan.readiness?`<p><strong>Session mode: ${escapeHTML(plan.readiness.mode)} · ${plan.readiness.score}/5</strong></p>`:''}<p class="small">Targets combine saved performance, fatigue history, accepted Coach adjustments and today's readiness. They are guidance, not automatic changes.</p>${plan.targets.map((t,i)=>`<article class="prism-coach-decision"><div class="journey-summary"><span>${i+1}. ${escapeHTML(t.mode)}</span><strong>${t.weight>0?`${escapeHTML(String(t.weight))} lb · `:''}${t.min}–${t.max} reps</strong></div><h4>${escapeHTML(t.name)}</h4><p class="small">Why: ${escapeHTML(t.reason)}</p></article>`).join('')}</div>`;}
function prismPreWorkoutMount(){const screen=document.getElementById('workoutScreen');if(!screen)return;let host=document.getElementById('prismPreWorkoutPlan');if(!host){host=document.createElement('div');host.id='prismPreWorkoutPlan';host.className='hidden';const focus=document.getElementById('prismWorkoutFocus');if(focus)focus.insertAdjacentElement('beforebegin',host);else screen.prepend(host);}prismPreWorkoutRender();}
window.prismPreWorkoutPlan=prismPreWorkoutPlan;window.prismPreWorkoutRender=prismPreWorkoutRender;window.prismPreWorkoutMount=prismPreWorkoutMount;
if(typeof openWorkout==='function'&&!openWorkout.__prismPreWorkout){const original=openWorkout;openWorkout=function(...args){const value=original.apply(this,args);setTimeout(prismPreWorkoutMount,0);return value;};openWorkout.__prismPreWorkout=true;window.openWorkout=openWorkout;}
