/* PRISM Pro Progress Photos beta. Images remain local in IndexedDB. */
const PRISM_PHOTO_DB='prismProgressPhotosDB',PRISM_PHOTO_STORE='photos',PRISM_PHOTO_VERSION=1;
let prismPhotoObjectURLs=[];
function prismPhotoDB(){return new Promise((resolve,reject)=>{if(!('indexedDB' in window)){reject(new Error('Photo storage is not supported on this browser.'));return;}const r=indexedDB.open(PRISM_PHOTO_DB,PRISM_PHOTO_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(PRISM_PHOTO_STORE)){const s=db.createObjectStore(PRISM_PHOTO_STORE,{keyPath:'id'});s.createIndex('date','date');s.createIndex('phaseId','phaseId');s.createIndex('view','view');}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Could not open photo storage.'));});}
async function prismPhotoAll(){const db=await prismPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PRISM_PHOTO_STORE,'readonly'),r=tx.objectStore(PRISM_PHOTO_STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date))));r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close();});}
async function prismPhotoPut(record){const db=await prismPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PRISM_PHOTO_STORE,'readwrite');tx.objectStore(PRISM_PHOTO_STORE).put(record);tx.oncomplete=()=>{db.close();resolve(record)};tx.onerror=()=>{db.close();reject(tx.error)};});}
async function prismPhotoDelete(id){const db=await prismPhotoDB();return new Promise((resolve,reject)=>{const tx=db.transaction(PRISM_PHOTO_STORE,'readwrite');tx.objectStore(PRISM_PHOTO_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();reject(tx.error)};});}
function prismPhotoPhaseForDate(date){if(typeof prismPhaseRead!=='function')return null;const day=new Date(`${date}T12:00:00`);return prismPhaseRead().find(p=>{const start=new Date(`${p.startDate}T00:00:00`),end=new Date(`${p.endDate||'2999-12-31'}T23:59:59`);return day>=start&&day<=end;})||null;}
function prismPhotoLabelPhase(id){if(!id||typeof prismPhaseRead!=='function')return '';const p=prismPhaseRead().find(x=>x.id===id);return p?((window.PRISM_GOAL_NAMES||{})[p.type]||p.type):'';}
function prismPhotoCompress(file,max=1600,quality=.82){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error('Could not prepare photo.'));},'image/jpeg',quality)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read photo.'))};img.src=url;});}
function prismPhotoGuessView(name,index,total){const n=String(name||'').toLowerCase();if(n.includes('front'))return'front';if(n.includes('side'))return'side';if(n.includes('back'))return'back';if(total===3)return ['front','side','back'][index];return'other';}
async function prismPhotoSaveFiles(files,date){const list=[...files].filter(f=>f.type.startsWith('image/')).slice(0,12);if(!list.length)throw new Error('Choose at least one image.');const phase=prismPhotoPhaseForDate(date);for(let i=0;i<list.length;i++){const file=list[i],blob=await prismPhotoCompress(file);await prismPhotoPut({id:`photo-${Date.now()}-${i}-${Math.random().toString(36).slice(2,7)}`,date,view:prismPhotoGuessView(file.name,i,list.length),phaseId:phase?.id||null,createdAt:new Date().toISOString(),blob});}return list.length;}
async function prismPhotoHandleUpload(event){event.preventDefault();const f=event.currentTarget,status=document.getElementById('prismPhotoStatus'),files=f.photos.files;if(status)status.textContent='Preparing photos…';try{const count=await prismPhotoSaveFiles(files,f.date.value);f.photos.value='';if(status)status.textContent=`Saved ${count} photo${count===1?'':'s'} privately on this device.`;await prismPhotoRender();}catch(err){if(status)status.textContent=err?.message||'Could not save photos.';}}
async function prismPhotoRemove(id){if(!confirm('Delete this progress photo from this device? This cannot be undone.'))return;await prismPhotoDelete(id);await prismPhotoRender();}
function prismPhotoURL(blob){const url=URL.createObjectURL(blob);prismPhotoObjectURLs.push(url);return url;}
function prismPhotoReleaseURLs(){for(const url of prismPhotoObjectURLs)URL.revokeObjectURL(url);prismPhotoObjectURLs=[];}
function prismPhotoDates(photos){return [...new Set(photos.map(p=>p.date).filter(Boolean))].sort();}
function prismPhotoDaysBetween(a,b){const A=new Date(`${a}T12:00:00`),B=new Date(`${b}T12:00:00`);return Math.max(0,Math.round((B-A)/86400000));}
function prismPhotoComparableViews(photos,before,after){return ['front','side','back'].filter(view=>photos.some(p=>p.date===before&&p.view===view)&&photos.some(p=>p.date===after&&p.view===view));}
function prismPhotoMeasurementHTML(before,after){if(typeof prismMeasurementComparisonHTML!=='function')return `<p class="small">Add Advanced Measurements to show weight and measurement changes with these photos.</p>`;return prismMeasurementComparisonHTML(before,after);}
function prismPhotoCompareHTML(photos,before,after,view){if(!before||!after||before>=after)return `<p class="small">Choose an earlier Before date and a later After date.</p>`;const first=photos.find(p=>p.date===before&&p.view===view),last=photos.find(p=>p.date===after&&p.view===view);if(!first||!last)return `<p class="small">PRISM needs a matching ${escapeHTML(view)} photo on both selected dates.</p>`;const days=prismPhotoDaysBetween(before,after),phaseA=prismPhotoLabelPhase(first.phaseId),phaseB=prismPhotoLabelPhase(last.phaseId),phaseText=phaseA&&phaseB?(phaseA===phaseB?phaseA:`${phaseA} → ${phaseB}`):(phaseA||phaseB||'No phase');return `<div class="journey-summary"><span>${escapeHTML(view.charAt(0).toUpperCase()+view.slice(1))} comparison</span><strong>${days} day${days===1?'':'s'}</strong></div><p class="small">${escapeHTML(before)} → ${escapeHTML(after)} · ${escapeHTML(phaseText)}</p><div class="prism-photo-compare" style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><figure><img src="${prismPhotoURL(first.blob)}" alt="Before ${escapeHTML(view)} progress photo"><figcaption><strong>Before</strong><br>${escapeHTML(before)}</figcaption></figure><figure><img src="${prismPhotoURL(last.blob)}" alt="After ${escapeHTML(view)} progress photo"><figcaption><strong>After</strong><br>${escapeHTML(after)}</figcaption></figure></div><div class="prism-photo-measurements"><h4>Body changes</h4>${prismPhotoMeasurementHTML(before,after)}</div>`;}
async function prismPhotoUpdateComparison(){const photos=await prismPhotoAll(),before=document.getElementById('prismPhotoBefore')?.value,after=document.getElementById('prismPhotoAfter')?.value,view=document.getElementById('prismPhotoView')?.value||'front',out=document.getElementById('prismPhotoComparisonResult');if(!out)return;prismPhotoReleaseURLs();out.innerHTML=prismPhotoCompareHTML(photos,before,after,view);}
function prismPhotoComparisonCard(photos){const dates=prismPhotoDates(photos);if(dates.length<2)return `<div class="card"><h3>Before vs After</h3><p class="small">Save progress photos on at least two different dates to unlock side-by-side comparisons.</p></div>`;const before=dates[0],after=dates[dates.length-1],views=prismPhotoComparableViews(photos,before,after),view=views[0]||'front';return `<div class="card"><span class="journey-eyebrow">PRISM PRO · TRANSFORMATION</span><h3>Before vs After</h3><p class="small">Compare matching photos, goal phase and measurements in one view.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><label>Before<input id="prismPhotoBefore" type="date" value="${before}" min="${dates[0]}" max="${dates[dates.length-1]}" onchange="prismPhotoUpdateComparison()"></label><label>After<input id="prismPhotoAfter" type="date" value="${after}" min="${dates[0]}" max="${dates[dates.length-1]}" onchange="prismPhotoUpdateComparison()"></label></div><label>View<select id="prismPhotoView" onchange="prismPhotoUpdateComparison()"><option value="front"${view==='front'?' selected':''}>Front</option><option value="side"${view==='side'?' selected':''}>Side</option><option value="back"${view==='back'?' selected':''}>Back</option></select></label><div id="prismPhotoComparisonResult">${prismPhotoCompareHTML(photos,before,after,view)}</div><p class="small">Measurements within 7 days of each selected photo date can be used for the comparison. Photos are shown side by side only; PRISM does not alter images or estimate body composition from appearance.</p></div>`;}
async function prismPhotoRender(){const host=document.getElementById('prismProgressPhotos');if(!host)return;prismPhotoReleaseURLs();if(typeof canAccessFeature==='function'&&!canAccessFeature('photo_comparison')){host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO ✦</span><h3>Progress Photos</h3><p class="small">Save Front, Side and Back photos privately on this device and connect them to your goal phases.</p><button type="button" onclick="showProPreview('photo_comparison')">Preview progress photos</button></div>`;return;}const today=new Date().toISOString().slice(0,10);let photos=[];try{photos=await prismPhotoAll();}catch(err){host.innerHTML=`<div class="card"><h3>Progress Photos</h3><p class="small">${escapeHTML(err?.message||'Photo storage is unavailable on this browser.')}</p></div>`;return;}const groups=new Map();for(const p of photos){const key=p.date;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p);}host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM PRO · PRIVATE</span><h3>Progress Photos</h3><p class="small">Photos are stored locally on this device. They are not uploaded to PRISM or GitHub.</p><form onsubmit="prismPhotoHandleUpload(event)"><label>Photo date<input name="date" type="date" value="${today}" max="${today}" required></label><label>Add photos<input name="photos" type="file" accept="image/*" multiple required></label><p class="small">You can select multiple photos at once. With exactly three photos, PRISM initially labels them Front, Side and Back in selection order.</p><button type="submit">Save Progress Photos</button><output id="prismPhotoStatus" role="status"></output></form></div>${prismPhotoComparisonCard(photos)}${photos.length?`<div class="card"><h3>Photo timeline</h3>${[...groups.entries()].map(([date,items])=>{const phase=prismPhotoLabelPhase(items[0]?.phaseId);return `<div class="prism-photo-group"><div class="journey-summary"><span>${escapeHTML(date)}</span><strong>${phase?escapeHTML(phase):'No phase'}</strong></div><div class="prism-photo-grid">${items.map(p=>`<figure><img src="${prismPhotoURL(p.blob)}" alt="${escapeHTML(p.view)} progress photo" loading="lazy"><figcaption>${escapeHTML(p.view.charAt(0).toUpperCase()+p.view.slice(1))}<button type="button" class="secondary" onclick="prismPhotoRemove('${escapeHTML(p.id)}')">Delete</button></figcaption></figure>`).join('')}</div></div>`}).join('')}</div>`:`<div class="card"><p class="small">No progress photos saved yet. Your first set will appear here.</p></div>`}`;}
function prismPhotoMount(){const screen=document.getElementById('overallProgressScreen');if(!screen)return;let host=document.getElementById('prismProgressPhotos');if(!host){host=document.createElement('div');host.id='prismProgressPhotos';const phases=document.getElementById('prismPhaseInsights');if(phases)phases.insertAdjacentElement('afterend',host);else screen.appendChild(host);}prismPhotoRender();}
window.prismPhotoAll=prismPhotoAll;window.prismPhotoPut=prismPhotoPut;window.prismPhotoDelete=prismPhotoDelete;window.prismPhotoSaveFiles=prismPhotoSaveFiles;window.prismPhotoRender=prismPhotoRender;window.prismPhotoMount=prismPhotoMount;window.prismPhotoHandleUpload=prismPhotoHandleUpload;window.prismPhotoRemove=prismPhotoRemove;window.prismPhotoUpdateComparison=prismPhotoUpdateComparison;window.prismPhotoCompareHTML=prismPhotoCompareHTML;
if(typeof showOverallProgress==='function'&&!showOverallProgress.__prismPhotos){const original=showOverallProgress;showOverallProgress=function(){original();prismPhotoMount();};showOverallProgress.__prismPhotos=true;}