/* PRISM Set Coach v1 — reacts to completed working sets without silently changing targets. */
const PRISM_SET_COACH_VERSION='1.0';
function prismSetCoachSafe(fn,fallback=null){try{const v=fn();return v==null?fallback:v}catch{return fallback}}
function prismSetCoachContext(){const saved=prismSetCoachSafe(()=>readPrismActiveWorkout(),null),ids=typeof activeWorkoutExerciseIds!=='undefined'?activeWorkoutExerciseIds:[],index=Math.max(0,Math.min(ids.length-1,Number(saved?.index)||0)),id=ids[index],ex=id?prismSetCoachSafe(()=>getExercise(id),null):null,key=typeof activeWorkoutKey!=='undefined'?activeWorkoutKey:null,sets=[];if(id&&key&&typeof setHistory!=='undefined')for(let n=1;n<=4;n++){const row=setHistory[`${key}-${id}-set${n}`];if(row&&Number(row.weight)>0&&Number(row.reps)>0)sets.push({set:n,weight:Number(row.weight),reps:Number(row.reps)});}return {saved,id,ex,key,sets};}
function prismSetCoachAnalyze(){const c=prismSetCoachContext();if(!c.ex||!c.sets.length)return null;const latest=c.sets[c.sets.length-1],previous=c.sets.length>1?c.sets[c.sets.length-2]:null,progression=prismSetCoachSafe(()=>progressionSuggestion(c.id),null),coach=prismSetCoachSafe(()=>prismCoachAnalyze(),null),signal=coach?.snapshot?.checkinSignal||null;let title=`Set ${latest.set} logged`,action='Repeat a clean working set and keep the next decision tied to performance.',why=`You completed ${latest.weight} lb × ${latest.reps}.`;
if(signal?.load==='conservative'){title='Recovery-first set guidance';action='Keep the next set controlled. Hold the load or reduce it if rep quality is dropping.';why=signal.reason||'Your Weekly Coach Check-In supports conservative loading.';}else if(previous&&latest.weight===previous.weight&&latest.reps<previous.reps-2){title='Performance is dropping';action='Keep the load stable or make a small reduction for the next set rather than forcing the target.';why=`Reps fell from ${previous.reps} to ${latest.reps} at ${latest.weight} lb.`;}else if(previous&&latest.weight===previous.weight&&latest.reps>=previous.reps){title='Set quality is holding';action='Keep the current load for the next set and try to stay inside the target rep range with clean execution.';why=`You maintained or improved reps at ${latest.weight} lb.`;}else if(progression?.status==='ready'&&latest.reps>=Number(progression.range?.max||12)){title='Top of the rep range';action='Finish the exercise with quality. PRISM can consider the next supported load increase for your next exposure.';why=`This set reached ${latest.reps} reps and your saved progression signal is ready.`;}
return {version:PRISM_SET_COACH_VERSION,...c,latest,previous,title,action,why};}
function prismSetCoachRender(){const host=document.getElementById('prismSetCoach');if(!host)return;const r=prismSetCoachAnalyze();if(!r){host.innerHTML='';host.classList.add('hidden');return;}host.classList.remove('hidden');host.innerHTML=`<div class="card"><span class="journey-eyebrow">PRISM COACH · SET ${r.latest.set}</span><h3>${escapeHTML(r.title)}</h3><p><strong>${escapeHTML(r.action)}</strong></p><p class="small">Why: ${escapeHTML(r.why)}</p></div>`;}
function prismSetCoachMount(){const workout=document.getElementById('workoutScreen');if(!workout)return;let host=document.getElementById('prismSetCoach');if(!host){host=document.createElement('div');host.id='prismSetCoach';host.className='hidden';const live=document.getElementById('prismInWorkoutCoach');if(live)live.insertAdjacentElement('afterend',host);else document.getElementById('prismWorkoutFocus')?.insertAdjacentElement('afterend',host);}prismSetCoachRender();}
function prismSetCoachRefresh(){prismSetCoachMount();prismSetCoachRender();}
window.prismSetCoachAnalyze=prismSetCoachAnalyze;window.prismSetCoachRender=prismSetCoachRender;window.prismSetCoachMount=prismSetCoachMount;window.prismSetCoachRefresh=prismSetCoachRefresh;
if(typeof focusWorkoutExercise==='function'&&!focusWorkoutExercise.__prismSetCoach){const original=focusWorkoutExercise;focusWorkoutExercise=function(...args){const value=original.apply(this,args);setTimeout(prismSetCoachRefresh,0);return value;};focusWorkoutExercise.__prismSetCoach=true;window.focusWorkoutExercise=focusWorkoutExercise;}
/* Set inputs are generated dynamically, so observe workout mutations and refresh only after saved set data changes. */
let prismSetCoachTimer=0;const prismSetCoachObserver=new MutationObserver(()=>{clearTimeout(prismSetCoachTimer);prismSetCoachTimer=setTimeout(prismSetCoachRender,80);});
function prismSetCoachObserve(){const list=document.getElementById('exerciseList');if(list)prismSetCoachObserver.observe(list,{subtree:true,childList:true,attributes:true,characterData:true});prismSetCoachMount();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',prismSetCoachObserve,{once:true});else prismSetCoachObserve();