/* PRISM Workout UX v1.0 — safe UI-only enhancement for the existing logger.
   Does not change workout storage, history, Coach data, or set picker logic. */
(() => {
  const STYLE_ID='prismWorkoutUxStyles';
  function addStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
  .tracking{padding:14px!important}.set-block{padding:14px 0!important}.set-row{grid-template-columns:44px minmax(0,1fr) minmax(0,1fr)!important;gap:10px!important}.set-label{font-size:13px!important;color:#666}.picker-button{min-height:52px!important;padding:12px 8px!important;border-radius:13px!important;font-size:16px!important}.previous{margin:8px 0 0 54px!important;line-height:1.35}.compare{margin:7px 0 0 54px!important}.prism-set-head{display:grid;grid-template-columns:44px minmax(0,1fr) minmax(0,1fr);gap:10px;align-items:end;margin:0 0 2px;color:#6e6e73;font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.04em}.prism-set-head span:first-child{color:transparent}.prism-workout-progress{position:sticky;top:calc(var(--header-height) + env(safe-area-inset-top));z-index:100;background:rgba(242,242,247,.94);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);padding:8px 0 10px;margin:-4px 0 10px}.prism-workout-progress-inner{background:#fff;border:1px solid #e5e5ea;border-radius:14px;padding:10px 12px;box-shadow:0 2px 8px rgba(0,0,0,.05)}.prism-workout-progress-row{display:flex;justify-content:space-between;gap:12px;align-items:center;font-size:13px}.prism-workout-progress-row strong{font-size:14px}.prism-workout-progress-track{height:6px;background:#e5e5ea;border-radius:99px;overflow:hidden;margin-top:8px}.prism-workout-progress-fill{height:100%;background:#111;border-radius:99px;transition:width .15s ease}.finish-workout{min-height:54px!important;position:relative}.finish-workout.prism-ready{box-shadow:0 0 0 3px rgba(40,167,69,.12)}@media(max-width:380px){.set-row,.prism-set-head{grid-template-columns:40px minmax(0,1fr) minmax(0,1fr);gap:7px}.picker-button{font-size:15px!important}.previous,.compare{margin-left:47px!important}}
  `;document.head.appendChild(s)}
  function workoutRoot(){const finish=document.querySelector('.finish-workout');return finish?.closest('.container,section,main,div')||null}
  function setBlocks(){return [...document.querySelectorAll('.set-block')].filter(x=>x.querySelector('.picker-button'))}
  function valueLooksLogged(btn){if(!btn)return false;const t=(btn.textContent||'').trim().toLowerCase();return !!t&&!['weight','reps','select','—','-','0'].includes(t)}
  function blockLogged(block){const buttons=[...block.querySelectorAll('.picker-button')];return buttons.length>=2&&buttons.every(valueLooksLogged)}
  function addHeaders(){document.querySelectorAll('.tracking').forEach(track=>{if(track.querySelector('.prism-set-head')||!track.querySelector('.set-row'))return;const h=document.createElement('div');h.className='prism-set-head';h.innerHTML='<span>Set</span><span>Weight</span><span>Reps</span>';const first=track.querySelector('.set-block');if(first)track.insertBefore(h,first)})}
  function updateProgress(){const blocks=setBlocks();if(!blocks.length){document.getElementById('prismWorkoutProgress')?.remove();return}const done=blocks.filter(blockLogged).length,total=blocks.length,pct=Math.round(done/total*100);let box=document.getElementById('prismWorkoutProgress');if(!box){box=document.createElement('div');box.id='prismWorkoutProgress';box.className='prism-workout-progress';box.innerHTML='<div class="prism-workout-progress-inner"><div class="prism-workout-progress-row"><strong>Workout progress</strong><span data-progress-text></span></div><div class="prism-workout-progress-track"><div class="prism-workout-progress-fill"></div></div></div>';const firstExercise=document.querySelector('.exercise');if(firstExercise)firstExercise.parentNode.insertBefore(box,firstExercise);else workoutRoot()?.prepend(box)}box.querySelector('[data-progress-text]').textContent=`${done} of ${total} sets logged`;box.querySelector('.prism-workout-progress-fill').style.width=`${pct}%`;const finish=document.querySelector('.finish-workout');if(finish)finish.classList.toggle('prism-ready',done===total&&total>0)}
  function enhance(){addStyles();addHeaders();updateProgress()}
  let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})}
  document.addEventListener('click',e=>{if(e.target.closest('.picker-button,.day-button,.workout-tab,.back'))setTimeout(schedule,60)},true);document.addEventListener('change',schedule,true);document.addEventListener('input',schedule,true);
  const observer=new MutationObserver(schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{enhance();observer.observe(document.body,{childList:true,subtree:true,characterData:true})},{once:true});else{enhance();observer.observe(document.body,{childList:true,subtree:true,characterData:true})}
  window.prismWorkoutUx={refresh:enhance,version:'1.0'};
})();
