const assert=require('assert'),fs=require('fs'),vm=require('vm');
const intelligence=fs.readFileSync('myliftcoach-intelligence-core.js','utf8');
const evidence=fs.readFileSync('myliftcoach-athlete-evidence-core.js','utf8');
const core=fs.readFileSync('athlete-learning-engine.js','utf8');
const overlay=fs.readFileSync('athlete-context-learning-v8.js','utf8');
const window={};const ctx={window,console,setTimeout};vm.createContext(ctx);vm.runInContext(intelligence,ctx);vm.runInContext(evidence,ctx);vm.runInContext(core,ctx);vm.runInContext(overlay,ctx);
const iso=d=>new Date(Date.now()-d*86400000).toISOString();
const ev=(id,exerciseId,days,opts={})=>({recommendationId:id,exerciseId,recommendationType:opts.type||'load_hold',completedAt:iso(days),followedRecommendation:opts.followed!==false,performanceDelta:opts.delta??.08,rpe:opts.rpe??7,pain:opts.pain??1,recoveryState:opts.recovery||'ready',phase:opts.phase||'hypertrophy'});
const events=[];
for(let i=0;i<6;i++)events.push(ev(`ready-${i}`,'press',[35,28,21,14,7,2][i],{delta:.08,rpe:7,pain:1,recovery:'ready'}));
for(let i=0;i<5;i++)events.push(ev(`strained-${i}`,'press',[34,27,20,13,4][i],{delta:-.05,rpe:9.5,pain:5,recovery:'strained'}));
const response=window.myliftcoachAthleteExerciseContexts(events,'press');
assert.strictEqual(response.contexts['ready|followed|hypertrophy'].state,'usable');
assert.strictEqual(response.contexts['strained|followed|hypertrophy'].state,'usable');
assert.ok(response.contexts['ready|followed|hypertrophy'].responseScore>response.contexts['strained|followed|hypertrophy'].responseScore+.2);
assert.strictEqual(response.bestContext.context.recovery,'ready');
const stale=[ev('s1','row',170),ev('s2','row',160),ev('s3','row',150),ev('s4','row',140)];
assert.strictEqual(window.myliftcoachAthleteExerciseContexts(stale,'row').contexts['ready|followed|hypertrophy'].state,'stale');
const contradictory=[ev('o1','leg',80,{delta:.1,recovery:'ready'}),ev('o2','leg',70,{delta:.1,recovery:'ready'}),ev('o3','leg',60,{delta:.1,recovery:'ready'}),ev('n1','leg',14,{delta:-.12,rpe:9.5,pain:5,recovery:'strained'}),ev('n2','leg',4,{delta:-.12,rpe:9.5,pain:5,recovery:'strained'})];
const c=window.myliftcoachAthleteExerciseContexts(contradictory,'leg');
assert.ok(Object.values(c.contexts).some(x=>x.state==='contradictory')===false,'different recovery contexts should not be falsely combined');
const sameContext=[ev('o1','curl',80,{delta:.1}),ev('o2','curl',70,{delta:.1}),ev('o3','curl',60,{delta:.1}),ev('n1','curl',14,{delta:-.12}),ev('n2','curl',4,{delta:-.12})];
assert.strictEqual(window.myliftcoachAthleteExerciseContexts(sameContext,'curl').contexts['ready|followed|hypertrophy'].state,'contradictory');
const map={press:['chest'],row:['back'],leg:['quads']};
const multi=[];for(const id of ['press','row','leg'])for(let i=0;i<6;i++)multi.push(ev(`${id}-${i}`,id,[35,28,21,14,7,2][i],{delta:.08}));
const snap=window.myliftcoachAthleteContextSnapshot(multi,map);
assert.strictEqual(snap.programContextReadiness.ready,true);assert.strictEqual(snap.guardrails.mayOverrideAdaptive,false);
const foundation=window.liftovaLearnProgramFoundation(multi,map);
assert.ok(foundation.contextLearning);assert.strictEqual(foundation.programReadiness.contextReady,true);
console.log(JSON.stringify({suite:'MYLIFTCOACH Athlete Context Learning V8',checks:{productionCorePath:true,contextSegmentation:true,readyVsStrained:true,staleExpiry:true,contradictionHandling:true,programContextReadiness:true,adaptiveAuthority:true}},null,2));
