const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const store=new Map(),localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
let owner='A';const window={workoutHistory:[],myliftcoachIntelligenceCore:{account:()=>({valid:true,owner})}},ctx={window,localStorage,console,Date,Object,JSON,Number,String,Boolean,Math,Array,RegExp,setTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync('adaptive-feedback-loop.js','utf8'),ctx,{filename:'adaptive-feedback-loop.js'});
const goodContext={movementType:'horizontal_push',fatigueState:'low',recoveryTiming:'normal',progressionTempo:'responsive',trainingPhase:'build'};
function explain(overrides={}){return {forecastSignal:'increase',modelConfidence:.9,historicalReliability:.92,confidence:.8,reasonCodes:[],context:goodContext,calibration:{state:'well_calibrated',count:10,drift:{detected:false}},...overrides};}
window.myliftcoachCoachForecastExplain=()=>explain();
const base={exerciseId:'press',status:'increase',targetWeight:105,lastWeight:100,workingSets:3,repMin:8,repMax:12,reason:'Adaptive approved increase',source:'adaptive_v2'};
let out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.targetWeight,105);assert.equal(out.workingSets,3);assert.equal(out.repMin,8);assert.equal(out.repMax,12);assert.equal(out.source,'adaptive_v2');assert.equal(out.forecastInfluence.confirmed,true);assert.equal(out.forecastInfluence.changed,false);assert.equal(out.forecastInfluence.direction,'increase_confirmation');
window.myliftcoachCoachForecastExplain=()=>explain({confidence:.73});out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.forecastInfluence.confirmationGates.confidence,false);
window.myliftcoachCoachForecastExplain=()=>explain({calibration:{state:'watch',count:10,drift:{detected:false}}});out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.forecastInfluence.confirmationGates.wellCalibrated,false);
window.myliftcoachCoachForecastExplain=()=>explain({calibration:{state:'well_calibrated',count:5,drift:{detected:false}}});out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.forecastInfluence.confirmationGates.sampled,false);
window.myliftcoachCoachForecastExplain=()=>explain({context:{...goodContext,recoveryTiming:'short'}});out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.status,'increase');
window.myliftcoachCoachForecastExplain=()=>explain({context:{...goodContext,fatigueState:'high'}});out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.status,'increase');
window.myliftcoachCoachForecastExplain=()=>explain();for(const status of ['recovery_hold','plateau_hold','feedback_hold','hold']){out=window.liftovaForecastInfluence({...base,status,targetWeight:100});assert.equal(out.forecastInfluence.confirmed,false);assert.equal(out.status,status);assert.equal(out.targetWeight,100);}
const badHistory=Array.from({length:4},(_,i)=>({id:'bad'+i,exerciseId:'press',context:goodContext,interventionType:'increase_confirmation',outcome:i<3?'harmful':'helpful',status:'resolved'}));store.set('myliftcoachForecastInfluenceOutcomesV1:A',JSON.stringify({pending:[],outcomes:badHistory}));out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmationOutcomeProfile.suspended,true);assert.equal(out.forecastInfluence.confirmed,false);
owner='B';out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmationOutcomeProfile.count,0);assert.equal(out.forecastInfluence.confirmed,true);
owner='A';out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,false);
owner='C';const goodHistory=Array.from({length:8},(_,i)=>({id:'good'+i,exerciseId:'press',context:goodContext,interventionType:'increase_confirmation',outcome:'helpful',status:'resolved'}));store.set('myliftcoachForecastInfluenceOutcomesV1:C',JSON.stringify({pending:[],outcomes:goodHistory}));out=window.liftovaForecastInfluence(base);assert.equal(out.forecastInfluence.confirmed,true);assert.equal(out.targetWeight,105);assert.equal(out.workingSets,3);assert.equal(out.repMin,8);assert.equal(out.repMax,12);assert.equal(out.forecastInfluence.confirmationOutcomeProfile.trustFactor,1);
console.log('V9.6 controlled bidirectional adaptation: strict positive confirmation, exact prescription preservation, recovery/fatigue vetoes, harmful-history suspension, helpful-history non-escalation, and A→B→A isolation pass.');