const assert=require('assert'),fs=require('fs'),vm=require('vm');
const validation=fs.readFileSync('myliftcoach-program-outcome-validation.js','utf8');
const policySource=fs.readFileSync('coach-program-overlay-policy.js','utf8');
class MemoryStorage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
const localStorage=new MemoryStorage();
const baseReview={version:'7.4',proposal:{type:'program_recovery',title:'Program recovery adjustment',reason:'Repeated weak responses.',requiresApproval:true,reversible:true,preserveProgramSource:true,authority:'adaptive_programming'}};
const legacyPolicy=()=>({version:'7.6',proposalType:'program_recovery',evidence:6,state:'working',confidence:1,successRate:.9,mayInformProgramming:true,mayOverrideAdaptive:false});
const window={myliftcoachProgramOverlayPolicy:legacyPolicy,prismCoachProgramReview:()=>JSON.parse(JSON.stringify(baseReview))};
const ctx={window,localStorage,console,setTimeout};vm.createContext(ctx);vm.runInContext(validation,ctx);vm.runInContext(policySource,ctx);
let review=window.prismCoachProgramReview();
assert.ok(review.proposal,'positive directional history without measured validation must not block the base proposal');
assert.strictEqual(review.proposal.requiresApproval,true);
assert.strictEqual(review.proposal.outcomePolicy.validatedSupport,false,'directional history alone must not count as validated support');
assert.match(review.proposal.outcomePolicy.support,/not strong enough/i);
const helpful=id=>({id,proposalType:'program_recovery',pre:{performance:[.5,.5,.51,.49,.5,.5],completion:[.8,.8,.79,.81,.8,.8],recovery:[.65,.65,.64,.66,.65,.65]},post:{performance:[.59,.58,.60,.59,.58,.60],completion:[.86,.85,.87,.86,.85,.87],recovery:[.69,.68,.70,.69,.68,.70]}});
localStorage.setItem('myliftcoachProgramOutcomeTrialsV1',JSON.stringify([helpful('1'),helpful('2'),helpful('3')]));
review=window.prismCoachProgramReview();
assert.ok(review.proposal);
assert.strictEqual(review.proposal.requiresApproval,true,'validated support still requires explicit approval');
assert.strictEqual(review.proposal.outcomePolicy.validatedSupport,true);
assert.strictEqual(review.proposal.outcomePolicy.validation.state,'validated_helpful');
assert.strictEqual(review.outcomePolicyDecision.authority,'adaptive_programming');
assert.strictEqual(review.outcomePolicyDecision.mayOverrideAdaptive,false);
const audit=window.myliftcoachProgramOutcomePolicyAudit();
assert.strictEqual(audit.guardrails.validatedImprovementRequiredForPositiveSupport,true);
assert.strictEqual(audit.guardrails.noAutomaticAcceptance,true);
assert.strictEqual(audit.guardrails.noAutomaticActivation,true);
assert.strictEqual(audit.guardrails.noProgramMutation,true);
assert.strictEqual(audit.guardrails.adaptiveProgrammingFinalAuthority,true);
console.log(JSON.stringify({suite:'MYLIFTCOACH V7.8 Outcome Validation + V7.7 Policy Integration',checks:{directionalHistoryNotEnough:true,measuredSupportRecognized:true,approvalStillRequired:true,noAutoActivation:true,noProgramMutation:true,adaptiveAuthority:true}},null,2));
