const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('liftova-quick-log.js','utf8');
const css=fs.readFileSync('liftova-quick-log.css','utf8');
const cfg=fs.readFileSync('supabase-config.js','utf8');
assert.doesNotThrow(()=>new Function(js));
assert.ok(js.includes("weight-minus"));
assert.ok(js.includes("weight-plus"));
assert.ok(js.includes("reps-minus"));
assert.ok(js.includes("reps-plus"));
assert.ok(js.includes("USE LAST SET VALUES"));
assert.ok(js.includes("window.saveSet"));
assert.ok(js.includes("✓ LOG SET"));
assert.ok(js.includes("startWorkoutRest")===false,'quick logger should preserve the proven core complete-set path rather than duplicate rest logic');
assert.ok(css.includes('.liftova-quick-log'));
assert.ok(css.includes('.liftova-one-tap-done'));
assert.ok(cfg.includes('liftova-quick-log.js?v=1'));
assert.ok(!js.includes('observe(document.body'));
console.log('LIFTOVA quick logging checks: OK');
