const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const data=new Map(),localStorage={getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v))};const window={localStorage};const ctx={window,localStorage,console,setTimeout:()=>0,Date,Object,JSON,Number,String,Boolean,Math,Array,RegExp,Set};vm.createContext(ctx);const run=f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
run('myliftcoach-intelligence-core.js');run('athlete-program-adaptation-outcomes-v8_7.js');
window.myliftcoachProgramAdaptationPlan=()=>({version:'8.6',state:'proposed',proposals:[{id:'p1',type:'temporary_volume_reduction',exerciseIds:['press'],confidence:.78,changes:{setDelta:-1,durationExposures:2,noLoadIncrease:true},requiresApproval:true,autoApply:false}],guardrails:{}});
window.myliftcoachAdaptiveProgramPlanReview=plan=>({version:'8.6',state:'review_ready',approved:[...plan.proposals],rejected:[],guardrails:{},authority:'adaptive_programming',autoApply:false});
run('myliftcoach-program-adaptation-planner-v8_7.js');run('myliftcoach-adaptive-program-outcomes-v8_7.js');
function complete(id,value){const p={id,type:'temporary_volume_reduction',exerciseIds:['press'],confidence:.78,changes:{setDelta:-1,durationExposures:2}};window.myliftcoachRememberProgramAdaptation(p);window.myliftcoachProgramAdaptationRespond(id,'approved');window.myliftcoachProgramAdaptationFollowThrough(id,'followed');window.myliftcoachProgramAdaptationOutcome(id,value,{performanceDelta:value==='better'?.08:-.08,fatigueDelta:value==='better'?-.1:.1,recoveryDelta:value==='better'?.1:-.1});}
for(let i=0;i<4;i++)complete('good'+i,'better');let plan=window.myliftcoachProgramAdaptationPlan({exerciseIds:['press','row']});assert.equal(plan.proposals.length,1);assert.equal(plan.proposals[0].programOutcomeHistory.state,'helpful');assert.equal(plan.proposals[0].confidence,.78);assert.equal(plan.proposals[0].changes.setDelta,-1);let review=window.myliftcoachAdaptiveProgramPlanReview(plan);assert.equal(review.approved.length,1);assert.equal(review.approved[0].adaptiveOutcomeReview.state,'historically_supported_same_bounds');assert.equal(review.approved[0].changes.durationExposures,2);
for(let i=0;i<10;i++)complete('bad'+i,'worse');plan=window.myliftcoachProgramAdaptationPlan({exerciseIds:['press','row']});assert.equal(plan.proposals.length,0);assert.equal(plan.suppressedByOutcomeHistory.length,1);assert.equal(plan.state,'history_blocked');
const forced={version:'8.6',state:'review_ready',approved:[{id:'forced',type:'temporary_volume_reduction',exerciseIds:['press'],confidence:.78,changes:{setDelta:-1,durationExposures:2},requiresApproval:true,autoApply:false}],rejected:[],guardrails:{},authority:'adaptive_programming',autoApply:false};review=window.myliftcoachAdaptiveProgramOutcomeApply(forced);assert.equal(review.approved.length,0);assert.equal(review.rejected[0].adaptiveOutcomeReview.reason,'harmful_program_outcome_history');
console.log(JSON.stringify({suite:'MYLIFTCOACH V8.7 Planner + Adaptive Outcome Review',checks:{helpfulRepeatSameBounds:true,noConfidenceEscalation:true,noMagnitudeEscalation:true,harmfulHistorySuppressesPlanner:true,harmfulHistoryRejectedByAdaptive:true,adaptiveFinalAuthority:true}},null,2));