const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('liftova-anatomy-v4.js','utf8');
const css=fs.readFileSync('liftova-anatomy-v4.css','utf8');
const cfg=fs.readFileSync('supabase-config.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert.doesNotThrow(()=>new Function(js));
for(const id of ['machine-chest-press','incline-chest-press','pec-deck','lat-pulldown','seated-row','shoulder-press','lateral-raise','triceps-pushdown']) assert.ok(js.includes(id));
for(const muscle of ['chest','upper-chest','lats','mid-back','delts','side-delts','triceps','biceps','rear-delts','traps']) assert.ok(js.includes(muscle));
assert.ok(css.includes('.m.primary'));assert.ok(css.includes('.m.secondary'));
assert.ok(cfg.includes('liftova-anatomy-v4.js?v=1'));
assert.ok(cfg.indexOf('liftova-anatomy-v4.js?v=1')>cfg.indexOf('liftova-workout-tab-v3.js?v=1'));
assert.ok(html.includes('apple-mobile-web-app-title\" content=\"LIFTOVA'));
assert.ok(html.includes('apple-touch-icon\" href=\"images/liftova-icon.svg?v=2'));
assert.ok(html.includes('<title>LIFTOVA · Train · Track · Progress</title>'));
assert.ok(!html.includes('<title>PRISM'));
assert.ok(sw.includes('beta40.8-liftova-anatomy'));
assert.ok(!js.includes('new MutationObserver'));
console.log('LIFTOVA detailed anatomy + installed branding checks: OK');