const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const window={workoutHistory:[]},ctx={window,console,Date,Object,JSON,Number,String,Boolean,Math,Array,RegExp};vm.createContext(ctx);vm.runInContext(fs.readFileSync('adaptive-feedback-loop.js','utf8'),ctx,{filename:'adaptive-feedback-loop.js'});
const base={exerciseId:'press',name:'Chest Press',status:'increase',targetWeight:110,lastWeight:100,workingSets:3,repMin:8,repMax:12,reason:'Progression threshold reached.',source:'adaptive_v2'};
function explain(overrides={}){return {coachState:'supported',forecastSignal:'hold',modelConfidence:.86,historicalReliability:.92,confidence:.79,reasonCodes:['high_fatigue'],calibration:{state:'well_calibrated',count:8,drift:{detected:false}},...overrides};}
window.myliftcoachCoachForecastExplain=()=>explain();
let out=window.liftovaForecastInfluence(base);assert.equal(out.status,'forecast_hold');assert.equal(out.targetWeight,100);assert.equal(out.workingSets,3);assert.equal(out.repMin,8);assert.equal(out.repMax,12);assert.equal(out.forecastInfluence.changed,true);assert.equal(out.forecastInfluence.eligible,true);assert.equal(out.forecastInfluence.guardrails.mayNeverCreateIncrease,true);assert.equal(out.forecastInfluence.guardrails.mayNeverReduceBelowPreviousLoad,true);
window.myliftcoachCoachForecastExplain=()=>explain({forecastSignal:'reduce'});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'forecast_hold');assert.equal(out.targetWeight,100,'even a reduce forecast may only hold the prior load');
window.myliftcoachCoachForecastExplain=()=>explain({forecastSignal:'increase'});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.targetWeight,110);assert.equal(out.forecastInfluence.changed,false);
window.myliftcoachCoachForecastExplain=()=>explain({confidence:.6});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.forecastInfluence.gates.confidence,false);
window.myliftcoachCoachForecastExplain=()=>explain({historicalReliability:.7});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.forecastInfluence.gates.historicalReliability,false);
window.myliftcoachCoachForecastExplain=()=>explain({calibration:{state:'learning',count:2,drift:{detected:false}}});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.forecastInfluence.gates.calibrated,false);
window.myliftcoachCoachForecastExplain=()=>explain({calibration:{state:'well_calibrated',count:12,drift:{detected:true}}});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.forecastInfluence.gates.noDrift,false);
window.myliftcoachCoachForecastExplain=()=>explain({reasonCodes:[]});out=window.liftovaForecastInfluence(base);assert.equal(out.status,'increase');assert.equal(out.forecastInfluence.gates.contextCorroborated,false);
window.myliftcoachCoachForecastExplain=()=>explain();const alreadyHeld={...base,status:'recovery_hold',targetWeight:100};out=window.liftovaForecastInfluence(alreadyHeld);assert.equal(out.status,'recovery_hold');assert.equal(out.targetWeight,100);assert.equal(out.forecastInfluence.gates.baseIncrease,false);
let active='A';window.myliftcoachCoachForecastExplain=()=>active==='A'?explain({reasonCodes:['short_recovery']}):explain({forecastSignal:'increase',reasonCodes:[]});const a1=window.liftovaForecastInfluence(base);active='B';const b=window.liftovaForecastInfluence(base);active='A';const a2=window.liftovaForecastInfluence(base);assert.equal(a1.status,'forecast_hold');assert.equal(b.status,'increase');assert.equal(a2.status,'forecast_hold','A→B→A must re-read live account-scoped forecast evidence with no cached crossover');
console.log('V9.4 bounded forecast influence: increase→hold only, no load reduction below prior, no set/rep/schedule mutation, confidence/reliability/calibration/drift/context gates, existing holds preserved, A→B→A live evidence isolation pass.');
