const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('coach-program-overlay-policy.js','utf8');
let policyState={version:'7.6',proposalType:'program_recovery',evidence:4,state:'rethink',confidence:.667,successRate:.25,mayInformProgramming:true,mayOverrideAdaptive:false};
const baseReview={version:'7.4',proposal:{type:'program_recovery',title:'Program recovery adjustment',reason:'Repeated weak responses.',requiresApproval:true,reversible:true,preserveProgramSource:true,authority:'adaptive_programming'}};
const window={myliftcoachProgramOverlayPolicy:()=>policyState,prismCoachProgramReview:()=>JSON.parse(JSON.stringify(baseReview))};
const ctx={window,console,setTimeout};vm.createContext(ctx);vm.runInContext(source,ctx);
let review=window.prismCoachProgramReview();
assert.strictEqual(review.proposal,null,'credible harmful overlay history must block repeating the same proposal');
assert.strictEqual(review.outcomePolicyDecision.allowed,false);
assert.strictEqual(review.outcomePolicyDecision.policy.state,'rethink');
assert.strictEqual(review.outcomePolicyDecision.mayOverrideAdaptive,false);
assert.strictEqual(review.outcomePolicyDecision.preserveProgramSource,true);
policyState={version:'7.6',proposalType:'program_recovery',evidence:4,state:'working',confidence:.667,successRate:.875,mayInformProgramming:true,mayOverrideAdaptive:false};
review=window.prismCoachProgramReview();
assert.ok(review.proposal,'helpful history may support reconsidering a proposal');
assert.strictEqual(review.proposal.requiresApproval,true,'helpful history must not auto-approve');
assert.strictEqual(review.proposal.outcomePolicy.state,'working');
assert.strictEqual(review.proposal.outcomePolicy.mayOverrideAdaptive,false);
assert.strictEqual(review.proposal.preserveProgramSource,true);
policyState={version:'7.6',proposalType:'program_recovery',evidence:1,state:'learning',confidence:.167,successRate:1,mayInformProgramming:false,mayOverrideAdaptive:false};
review=window.prismCoachProgramReview();
assert.ok(review.proposal,'insufficient outcome evidence must not block the base proposal');
const direct=window.myliftcoachProgramOutcomePolicyEvaluate(baseReview.proposal);assert.strictEqual(direct.allowed,true);assert.strictEqual(direct.authority,'adaptive_programming');
const audit=window.myliftcoachProgramOutcomePolicyAudit();assert.strictEqual(audit.guardrails.noAutomaticAcceptance,true);assert.strictEqual(audit.guardrails.noAutomaticActivation,true);assert.strictEqual(audit.guardrails.noProgramMutation,true);assert.strictEqual(audit.guardrails.noPresetFallback,true);assert.strictEqual(audit.guardrails.preserveProgramSource,true);assert.strictEqual(audit.guardrails.adaptiveProgrammingFinalAuthority,true);
console.log(JSON.stringify({suite:'MYLIFTCOACH Program Overlay Policy V7.7',checks:{harmfulRepeatBlocked:true,helpfulHistorySupportsOnly:true,approvalStillRequired:true,lowEvidenceAdvisory:true,noAutoActivation:true,noProgramMutation:true,noPresetFallback:true,adaptiveAuthority:true}},null,2));
