const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function make(){const data=new Map(),localStorage={getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};const window={localStorage};const ctx={window,localStorage,console,setTimeout:()=>0,Date,Object,JSON,Number,String,Boolean,Math,Array,RegExp};vm.createContext(ctx);for(const f of ['myliftcoach-intelligence-core.js','athlete-program-adaptation-outcomes-v8_7.js','myliftcoach-coach-program-outcomes-v8_7.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});return {window,data,ctx};}
const {window}=make();
function complete(id,type,outcome){const p={id,type,exerciseIds:['press'],plannerVersion:'8.6',confidence:.8,changes:{setDelta:-1,durationExposures:2}};window.myliftcoachRememberProgramAdaptation(p);window.myliftcoachProgramAdaptationRespond(id,'approved');window.myliftcoachProgramAdaptationFollowThrough(id,'followed');window.myliftcoachProgramAdaptationOutcome(id,outcome,{performanceDelta:outcome==='better'?.08:-.08,fatigueDelta:outcome==='better'?-.1:.1,recoveryDelta:outcome==='better'?.1:-.1});}
for(let i=0;i<4;i++)complete('h'+i,'temporary_volume_reduction','better');
const helpful=window.myliftcoachProgramAdaptationOutcomeProfile('temporary_volume_reduction');assert.equal(helpful.state,'helpful');assert.equal(helpful.maySupportRepeat,true);assert.equal(helpful.mayIncreaseMagnitude,false);assert.equal(helpful.mayExtendDuration,false);
for(let i=0;i<4;i++)complete('x'+i,'progression_cadence_hold','worse');
const harmful=window.myliftcoachProgramAdaptationOutcomeProfile('progression_cadence_hold');assert.equal(harmful.state,'harmful');assert.equal(harmful.mayBlockRepeat,true);
window.myliftcoachRememberProgramAdaptation({id:'rejected',type:'reduced_pressure_block',exerciseIds:['press'],changes:{durationExposures:2}});window.myliftcoachProgramAdaptationRespond('rejected','rejected');window.myliftcoachProgramAdaptationFollowThrough('rejected','not_followed');window.myliftcoachProgramAdaptationOutcome('rejected','better');assert.equal(window.myliftcoachProgramAdaptationOutcomeProfile('reduced_pressure_block').count,0);
const coach=window.myliftcoachCoachProgramOutcomeExplain('temporary_volume_reduction');assert.equal(coach.state,'helpful');assert.equal(coach.mayIncreaseMagnitude,false);assert.equal(coach.mayExtendDuration,false);
console.log(JSON.stringify({suite:'MYLIFTCOACH V8.7 Program Outcome Learning',checks:{helpfulPatternLearned:true,harmfulPatternLearned:true,rejectedNotFollowedExcluded:true,helpfulCannotEscalate:true,coachAdvisoryOnly:true,adaptiveAuthorityPreserved:true}},null,2));