const assert=require('node:assert/strict');
const fs=require('node:fs');
const js=fs.readFileSync('liftova-anatomy-v4.js','utf8');
const css=fs.readFileSync('liftova-anatomy-v4.css','utf8');
const cfg=fs.readFileSync('supabase-config.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
assert.doesNotThrow(()=>new Function(js));
for(const id of ['machine-chest-press','incline-chest-press','pec-deck','lat-pulldown','seated-row','shoulder-press','lateral-raise','triceps-pushdown']) assert.ok(js.includes(id));
for(const asset of ['images/liftova-workout-row-sprite.webp','images/liftova-chest-press-detail.webp','images/liftova-chest-anatomy.webp','images/apple-touch-icon-180.png']) assert.ok(fs.existsSync(asset), `${asset} must exist`);
assert.ok(js.includes("images/liftova-chest-press-detail.webp?v=1"));
assert.ok(js.includes("images/liftova-chest-anatomy.webp?v=1"));
assert.ok(js.includes("images/apple-touch-icon-180.png?v=4"));
assert.ok(js.includes('.lv3-ex-photo'));
assert.ok(js.includes('showPrismWorkoutDetail'));
assert.ok(js.includes('showExerciseInfo'));
assert.ok(css.includes("images/liftova-workout-row-sprite.webp?v=1"));
assert.ok(css.includes('background-size:200% 800%'));
assert.ok(css.includes('.lv5-photo-sprite'));
assert.ok(css.includes('.lv5-anatomy-sprite'));
assert.ok(css.includes('.lv5-realistic-detail'));
assert.ok(cfg.includes('liftova-anatomy-v4.js?v=2'));
assert.ok(cfg.indexOf('liftova-anatomy-v4.js?v=2')>cfg.indexOf('liftova-workout-tab-v3.js?v=1'));
assert.ok(html.includes('apple-mobile-web-app-title\" content=\"LIFTOVA'));
assert.ok(html.includes('<title>LIFTOVA · Train · Track · Progress</title>'));
assert.ok(!html.includes('<title>PRISM'));
assert.ok(manifest.icons.some(icon=>icon.src==='images/apple-touch-icon-180.png?v=4'&&icon.type==='image/png'));
assert.ok(sw.includes('beta40.9-liftova-exact'));
for(const asset of ['./images/liftova-workout-row-sprite.webp','./images/liftova-chest-press-detail.webp','./images/liftova-chest-anatomy.webp','./images/apple-touch-icon-180.png']) assert.ok(sw.includes(asset));
assert.ok(!js.includes('MutationObserver'));
console.log('LIFTOVA exact-reference imagery + installed branding checks: OK');
