const assert=require('assert'),fs=require('fs'),vm=require('vm');
const learning=fs.readFileSync('athlete-learning-engine.js','utf8');
const adaptation=fs.readFileSync('coach-program-adaptation.js','utf8');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const exerciseMeta={press:{name:'Chest Press',muscle:'chest'},fly:{name:'Chest Fly',muscle:'chest'},row:{name:'Seated Row',muscle:'back'},pulldown:{name:'Lat Pulldown',muscle:'back'}};
const window={getExercise:id=>exerciseMeta[id]||{name:id,muscle:'other'}};
const document={body:{appendChild(){}},querySelector(){return true},createElement(){return {dataset:{}}}};
const ctx={window,localStorage,document,console,setTimeout,Date,Math,JSON};vm.createContext(ctx);vm.runInContext(learning,ctx);
const now=Date.now();
const sessions=[];for(let s=0;s<3;s++){sessions.push({id:`s${s}`,date:new Date(now-s*5*86400000).toISOString(),exercises:Object.keys(exerciseMeta).map((id,i)=>({id,name:exerciseMeta[id].name,muscle:exerciseMeta[id].muscle,sets:[{reps:10,weight:100+i*10},{reps:9,weight:100+i*10},{reps:8,weight:100+i*10}]}))});}
localStorage.setItem('workoutHistoryV52',JSON.stringify(sessions));
const interventions=[];for(const id of Object.keys(exerciseMeta)){for(let i=0;i<8;i++){interventions.push({id:`${id}-${i}`,at:new Date(now-(i+1)*86400000).toISOString(),kind:'adaptive_prescription',exerciseId:id,response:{value:'followed',at:new Date(now-(i+1)*86400000).toISOString()},outcome:{value:id==='press'||id==='fly'?'worse':'better',at:new Date(now-i*86400000).toISOString()}})}}
localStorage.setItem('prismCoachInterventionsV1',JSON.stringify(interventions));
window.prismCoachConfidence=id=>({ready:true,score:.8});
window.prismExerciseCoachMemory=id=>({mode:id==='press'||id==='fly'?'conservative':'trusted',reason:id==='press'||id==='fly'?'Repeated weak response.':'Repeated positive response.'});
window.prismInterventionPolicy=id=>({signal:id==='press'||id==='fly'?'rethink':'working',reason:id==='press'||id==='fly'?'Recent interventions underperformed.':'Recent interventions performed well.'});
vm.runInContext(adaptation,ctx);
const beforeHistory=localStorage.getItem('workoutHistoryV52');
const review=window.prismCoachProgramReview();
assert.strictEqual(review.version,'7.4');
assert.strictEqual(review.authority,'adaptive_programming');
assert.strictEqual(review.mode,'advisory');
assert.strictEqual(review.preserveProgramSource,true);
assert.strictEqual(typeof review.learning,'number','legacy review.learning count remains compatible');
assert.strictEqual(review.evidence.ready,true);
assert.strictEqual(review.evidence.signal,'recovery');
assert.strictEqual(review.learningFoundation.available,true);
assert.strictEqual(review.evidence.learningReady,true);
assert.ok(review.learningFoundation.programReadiness.usableExercises>=3);
assert.ok(review.learningFoundation.programReadiness.usableMuscles>=2);
assert.ok(review.proposal);
assert.strictEqual(review.proposal.type,'program_recovery');
assert.strictEqual(review.proposal.requiresApproval,true);
assert.strictEqual(review.proposal.reversible,true);
assert.strictEqual(review.proposal.preserveProgramSource,true);
assert.strictEqual(review.proposal.authority,'adaptive_programming');
assert.ok(review.proposal.evidenceSources.includes('athlete_learning_v7_3'));
assert.strictEqual(localStorage.getItem('workoutHistoryV52'),beforeHistory,'completed workout history must remain read-only');
const first=window.prismCoachProgramProposal();assert.ok(first&&first.id);const second=window.prismCoachProgramProposal();assert.strictEqual(second.id,first.id,'duplicate proposal should be suppressed');
const accepted=window.prismCoachProgramRespond(first.id,'accepted');assert.strictEqual(accepted.status,'accepted');const undone=window.prismCoachProgramRespond(first.id,'undone');assert.strictEqual(undone.status,'undone');
const audit=window.prismCoachProgramAudit();assert.strictEqual(audit.guardrails.noUiMutation,true);assert.strictEqual(audit.guardrails.noAutomaticWorkoutReplacement,true);assert.strictEqual(audit.guardrails.noPresetFallback,true);assert.strictEqual(audit.guardrails.completedHistoryReadOnly,true);assert.strictEqual(audit.guardrails.learningIsSupportingEvidenceOnly,true);assert.strictEqual(audit.guardrails.adaptiveProgrammingFinalAuthority,true);assert.strictEqual(audit.learning.mayOverrideAdaptive,false);
console.log(JSON.stringify({suite:'Coach Program Adaptation V7.4',checks:{programEvidence:true,v73LearningBridge:true,muscleEvidence:true,legacyCompatibility:true,approvalRequired:true,reversible:true,duplicateSuppression:true,noPresetFallback:true,noUiMutation:true,historyReadOnly:true,adaptiveAuthority:true}},null,2));