const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const coach=fs.readFileSync('coach-engine.js','utf8');
const recovery=fs.readFileSync('coach-recovery-deload.js','utf8');
const names={chest:'Machine Chest Press',row:'Seated Row',legs:'Leg Press',shoulders:'Shoulder Press'};
const history=[];let week=0;
const weeklySignals=[{load:'normal',days:4,reason:'Normal recovery and energy.'},{load:'progressive',days:4,reason:'Recovery and energy are strong.'},{load:'conservative',days:3,reason:'Fatigue is elevated and schedule is tighter.'},{load:'normal',days:4,reason:'Recovery returned to normal.'}];
const program={1:{chest:[100,10],row:[120,10],legs:[220,10],shoulders:[70,10]},2:{chest:[105,10],row:[125,10],legs:[230,10],shoulders:[75,10]},3:{chest:[105,9],row:[125,9],legs:[235,10],shoulders:[75,9]},4:{chest:[105,10],row:[125,9],legs:[240,10],shoulders:[75,8]}};
function addWeek(w){const p=program[w],dates=[1,2,4,5].map(d=>`2026-09-${String((w-1)*7+d).padStart(2,'0')}`),ids=['chest','row','legs','shoulders'];ids.forEach((id,i)=>history.push({date:dates[i],exercises:[{id,name:names[id],sets:[{weight:p[id][0],reps:p[id][1]},{weight:p[id][0],reps:Math.max(1,p[id][1]-1)},{weight:p[id][0],reps:Math.max(1,p[id][1]-1)}]}]}));if(w===4){const extra=history.at(-1);extra.exercises.push({id:'chest',name:names.chest,sets:[{weight:105,reps:10},{weight:105,reps:10},{weight:105,reps:9}]});}}
function exerciseSessions(id){return history.filter(s=>s.exercises?.some(e=>e.id===id)).map(s=>s.exercises.find(e=>e.id===id));}
function progressionSuggestion(id){const rows=exerciseSessions(id);if(!rows.length)return null;const last=rows.at(-1),best=last.sets.reduce((a,b)=>a.reps>b.reps?a:b),lastWeight=Number(best.weight);if(rows.length<2)return {status:'learning',lastWeight,range:{min:8,max:10}};if(best.reps>=10)return {status:'ready',weight:lastWeight+5,lastWeight,range:{min:8,max:10},action:'increase_weight'};return {status:'hold',lastWeight,range:{min:8,max:10}};}
function confidence(id){const exposures=exerciseSessions(id).length;if(exposures>=5)return {level:'HIGH',exposures,score:.85,ready:true,autoProgress:true};if(exposures>=3)return {level:'MEDIUM',exposures,score:.55,ready:true,autoProgress:false};if(exposures>=1)return {level:'LOW',exposures,score:.25,ready:false,autoProgress:false};return {level:'LEARNING',exposures:0,score:0,ready:false,autoProgress:false};}
function plateauAnalyze(){const out=[];for(const id of Object.keys(names)){const rows=exerciseSessions(id);if(rows.length<4)continue;const last4=rows.slice(-4).map(e=>{const s=e.sets.reduce((a,b)=>a.reps>b.reps?a:b);return {weight:Number(s.weight),reps:Number(s.reps)}}),first=last4[0],last=last4[3],score=x=>x.weight*(1+x.reps/30),gain=(score(last)-score(first))/score(first);if(gain<.02)out.push({id,name:names[id],reason:'Four comparable exposures without at least 2% estimated performance improvement.'});}return out;}
const ctx={console,Math,Number,String,Date,Map,JSON,window:{workoutHistory:history,workoutGoals:{days:4},PRISM_GOAL_NAMES:{maintain:'Maintain'}},workoutHistory:history,getExercise:id=>({name:names[id]||id}),progressionSuggestion,prismCoachConfidence:confidence,prismPlateauAnalyze:plateauAnalyze,prismActivePhase:()=>({id:'phase-1',type:'maintain',startDate:'2026-09-01'}),prismMeasurementRead:()=>[],prismWeeklySummaryData:()=>({workouts:4,sets:12}),prismCheckinCurrent:()=>weeklySignals[week-1],prismCheckinCoachSignal:x=>x,prismAthleteCoachContext:()=>({goal:'hypertrophy',priority:'time',equipment:'mostly_machines',days:4,sessionMinutes:45,summary:'Hypertrophy, 4 days, mostly machines, 45 minutes'}),canAccessFeature:()=>true,escapeHTML:v=>String(v),escapeAttribute:v=>String(v),document:{getElementById:()=>null,createElement:()=>({})},showOverallProgress:function(){},localStorage:{getItem:()=>null,setItem:()=>{}}};
vm.createContext(ctx);vm.runInContext(coach,ctx);const report=[];
for(week=1;week<=4;week++){addWeek(week);const before=JSON.stringify(history),r=ctx.prismCoachAnalyze();assert.equal(JSON.stringify(history),before,'Coach must not mutate simulated history');report.push({week,top:r.decisions[0]?.title||null,decisions:r.decisions.map(d=>({source:d.source,title:d.title,action:d.action,target:d.meta?.targetWeight||null,proposed:d.meta?.proposedWeight||null,evidence:d.meta?.coachEvidence||null}))});}
assert.ok(report[0].decisions.some(d=>d.source==='smart_progression'),'Week 1 should establish performance guidance.');
assert.ok(report[1].decisions.some(d=>d.source==='smart_progression'&&/Build confidence/.test(d.title)),'Week 2 should not increase load on only two exposures.');
assert.ok(!report[1].decisions.some(d=>d.evidence?.autoProgress),'Week 2 must not claim high-confidence auto progression.');
assert.equal(report[2].top,'Prioritize recovery this week','Week 3 elevated fatigue should outrank progression.');
assert.ok(report[2].decisions.some(d=>d.title.includes('Plan around 3 training days')),'Week 3 should adapt to reduced schedule availability.');
assert.ok(report[2].decisions.some(d=>d.source==='coach_checkin'&&/Hold/.test(d.title)),'Week 3 should override a ready progression signal with a recovery hold.');
assert.ok(report[3].decisions.some(d=>d.source==='plateau_detection'),'Week 4 should surface stalled exercises.');
assert.ok(report[3].decisions.some(d=>d.source==='smart_progression'&&/Prove/.test(d.title)),'Week 4 should require medium-confidence exercises to prove the top range again.');
assert.ok(report[3].decisions.some(d=>d.source==='smart_progression'&&/Progress Machine Chest Press/.test(d.title)&&d.evidence?.autoProgress===true),'A fifth clean Chest Press exposure should unlock a true high-confidence load increase.');
const store={prismSessionFatigueV1:JSON.stringify([{fatigue:'high'},{fatigue:'recovery'},{fatigue:'moderate'},{fatigue:'moderate'}])};const rc={console,Math,Number,String,Date,JSON,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},window:{prismCoachProgramReview:()=>({plateau:2,items:[1,2,3,4]}),dispatchEvent:()=>{}},CustomEvent:function(){}};rc.window.window=rc.window;vm.createContext(rc);vm.runInContext(recovery,rc);const recoveryResult=rc.window.prismCoachRecoveryAnalyze();assert.equal(recoveryResult.state,'deload_candidate');assert.equal(recoveryResult.recommendation.loadReductionPct,10);assert.equal(recoveryResult.recommendation.volumeReductionPct,25);assert.equal(recoveryResult.requiresApproval,true);
console.log('\n=== LIFTOVA COACH V1.4: 4-WEEK CONFIDENCE SIMULATION ===');for(const w of report){console.log(`\nWeek ${w.week} — top priority: ${w.top}`);w.decisions.forEach((d,i)=>console.log(`${i+1}. [${d.source}] ${d.title} -> ${d.action}${d.target?` (target ${d.target} lb)`:''}${d.proposed&&d.proposed!==d.target?` (future ${d.proposed} lb)`:''}${d.evidence?` [${d.evidence.level}/${d.evidence.exposures} exposures]`:''}`));}console.log(`\nRecovery engine: ${recoveryResult.state}; ${recoveryResult.recommendation.title}; load -${recoveryResult.recommendation.loadReductionPct}%, volume -${recoveryResult.recommendation.volumeReductionPct}%; approval required.`);console.log('\nCONFIDENCE MONTH SIMULATION: PASS');