const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('coach-program-overlays.js','utf8');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v))};
const window={};
let outcomeCalls=0;
window.prismAdaptivePrescription=id=>({exerciseId:id,targetWeight:110,lastWeight:100,workingSets:4,status:'increase',reason:'Base adaptive increase',source:'adaptive'});
window.prismInterventionOutcome=(id,outcome)=>{outcomeCalls++;return {exerciseId:id,outcome}};
window.prismCoachProgramRespond=(id,status)=>{const rows=JSON.parse(localStorage.getItem('prismCoachProgramProposalsV1')||'[]'),p=rows.find(x=>x.id===id);if(!p)return null;p.status=status;localStorage.setItem('prismCoachProgramProposalsV1',JSON.stringify(rows));return p};
const proposal={id:'pp-1',status:'proposed',requiresApproval:true,reversible:true,type:'program_recovery',changes:[{exerciseId:'press',exercise:'Chest Press',change:'Hold load and reduce progression pressure.',reason:'Repeated weak response.'}]};
localStorage.setItem('prismCoachProgramProposalsV1',JSON.stringify([proposal]));
const ctx={window,localStorage,console,setTimeout:(fn)=>fn(),Date,Math,JSON};vm.createContext(ctx);vm.runInContext(source,ctx);
assert.strictEqual(window.MYLIFTCOACH_PROGRAM_OVERLAY_VERSION,'7.5');
assert.strictEqual(window.myliftcoachProgramOverlayActivate('pp-1'),null,'unaccepted proposal must not activate');
const accepted=window.prismCoachProgramRespond('pp-1','accepted');assert.ok(accepted);
const audit1=window.myliftcoachProgramOverlayAudit();assert.strictEqual(audit1.active,1);
const rx=window.prismAdaptivePrescription('press');
assert.strictEqual(rx.status,'program_recovery_hold');
assert.strictEqual(rx.targetWeight,100,'overlay must not increase load above previous working load');
assert.strictEqual(rx.workingSets,3,'overlay may conservatively reduce one working set');
assert.strictEqual(rx.sourceProgramPreserved,true);
assert.strictEqual(rx.programOverlay.preserveProgramSource,true);
const other=window.prismAdaptivePrescription('row');assert.strictEqual(other.targetWeight,110,'unrelated exercise must remain unchanged');
window.prismInterventionOutcome('press','same');assert.strictEqual(outcomeCalls,1);
const audit2=window.myliftcoachProgramOverlayAudit();assert.strictEqual(audit2.active,0);assert.strictEqual(audit2.completed,1);
const post=window.prismAdaptivePrescription('press');assert.strictEqual(post.targetWeight,110,'completed overlay must stop constraining prescription');
const rows=JSON.parse(localStorage.getItem('myliftcoachProgramOverlaysV1'));assert.strictEqual(rows[0].status,'completed');
assert.strictEqual(audit2.guardrails.noExerciseRemoval,true);assert.strictEqual(audit2.guardrails.noPresetFallback,true);assert.strictEqual(audit2.guardrails.preserveProgramSource,true);assert.strictEqual(audit2.guardrails.adaptiveProgrammingFinalAuthority,true);
console.log(JSON.stringify({suite:'MYLIFTCOACH Program Overlays V7.5',checks:{acceptedOnly:true,temporary:true,reversible:true,noLoadIncrease:true,noVolumeIncrease:true,preserveProgramSource:true,noPresetFallback:true,outcomeExpiry:true,adaptiveAuthority:true}},null,2));
