const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const window={currentAccount:'A'},ctx={window,console,Date,Object,JSON,Number,String,Boolean,Math,Array,RegExp,setTimeout};vm.createContext(ctx);const run=f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});run('myliftcoach-intelligence-core.js');
function ready(overrides={}){const vals={performanceTrend:.76,adherence:.9,fatiguePressure:.2,fatigueTrend:.24,recoveryReadiness:.82,doseTolerance:.72,progressionTolerance:.8,contextReadiness:.8,priorAdaptationResponse:.72,...overrides};return {state:'ready',features:Object.fromEntries(Object.entries(vals).map(([k,v])=>[k,{value:v,confidence:.85}])),coverage:1,confidence:.86,uncertainty:.1};}
window.myliftcoachPredictiveAthleteState=()=>ready();
window.myliftcoachPredictionCalibrationProfile=(action,exerciseId,context)=>{
 if(window.currentAccount==='A'&&context.recoveryTiming==='short')return {state:'unreliable',count:9,brier:.34,trustFactor:.65,historicalReliability:.65,contextSpecific:true,drift:{detected:false}};
 if(window.currentAccount==='A')return {state:'well_calibrated',count:9,brier:.08,trustFactor:1,historicalReliability:1,contextSpecific:true,drift:{detected:false}};
 if(window.currentAccount==='B')return {state:'watch',count:12,brier:.17,trustFactor:.736,historicalReliability:.736,contextSpecific:true,drift:{detected:true,totalVariation:.5,errorDelta:.12}};
 return {state:'learning',count:0,trustFactor:1,historicalReliability:1,contextSpecific:false,drift:{detected:false}};
};
window.myliftcoachPredictionDiagnostics=()=>({weakestPredictionType:window.currentAccount==='B'?'increase':null});run('myliftcoach-predictive-athlete-model-v9.js');
const strong=window.myliftcoachCoachForecastExplain('press',{movementType:'horizontal_push',trainingPhase:'build',recoveryTiming:'extended',fatigueState:'low'});assert.equal(strong.historicalReliability,1);assert(!strong.reasonCodes.includes('contextual_reliability_reduced'));assert.equal(strong.mayChangeTraining,false);
const poor=window.myliftcoachCoachForecastExplain('press',{movementType:'horizontal_push',trainingPhase:'build',recoveryTiming:'short',fatigueState:'high'});assert.equal(poor.historicalReliability,.65);assert(poor.confidence<poor.modelConfidence);assert(poor.reasonCodes.includes('contextual_reliability_reduced'));assert(poor.reasonCodes.includes('short_recovery'));assert(poor.reasonCodes.includes('high_fatigue'));assert.match(poor.summary,/reduces trust/i);
window.currentAccount='B';const b=window.myliftcoachCoachForecastExplain('press',{movementType:'horizontal_push',trainingPhase:'build',recoveryTiming:'extended',fatigueState:'low'});assert.equal(b.historicalReliability,.736);assert(b.reasonCodes.includes('context_drift_detected'));assert.match(b.summary,/drifting/i);if(b.forecastSignal==='increase')assert(b.reasonCodes.includes('weakest_prediction_type'));assert.equal(b.mayRewriteProgram,false);assert.equal(b.authority,'adaptive_programming');
window.currentAccount='A';const aAgain=window.myliftcoachCoachForecastExplain('press',{movementType:'horizontal_push',trainingPhase:'build',recoveryTiming:'extended',fatigueState:'low'});assert.equal(aAgain.historicalReliability,1);assert(!aAgain.reasonCodes.includes('context_drift_detected'));assert.equal(aAgain.confidence,aAgain.modelConfidence);
const audit=window.myliftcoachPredictiveModelAudit();assert.equal(audit.guardrails.coachForecastReasoningAdvisoryOnly,true);assert.equal(audit.guardrails.coachReasoningCannotRewriteProgram,true);assert.equal(audit.guardrails.adaptiveProgrammingFinalAuthority,true);assert.equal(audit.guardrails.mayOverrideAdaptive,false);
console.log('V9.3 forecast-informed Coach milestone: local calibration, drift, context, A→B→A live reasoning, confidence separation, and Adaptive final authority pass.');