const assert=require('node:assert/strict');
const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');
const loader=read('supabase-config.js');
const detail=read('liftova-workout-tab-v3.js');
const css=read('liftova-reference-v3.css');
const base=read('myliftcoach-base.css');
const sw=read('sw.js');

assert.doesNotMatch(loader,/liftova-reference-v3\.js/,'retired duplicate presentation root must never load');
assert.ok(css.length>12000,'workout detail stylesheet must retain the full detail visual system');
assert.ok(base.length>1000,'MYLIFTCOACH base chrome stylesheet must be present');
assert.match(sw,/url\.pathname\.includes\("\/liftova-"\)/,'legacy-named assets remain network-first for cache-safe iOS/PWA delivery');
for(const marker of ['lv3-detail-top','lv3-tabs','lv3-workout-metrics','lv3-exercise-row','lv3-set-box','lv3-start-workout'])assert.match(detail,new RegExp(marker),`Workout detail module must render ${marker}`);
assert.match(detail,/LiftovaAnatomy\?\.render/,'workout rows must use shared anatomy rendering');
assert.match(detail,/LiftovaAnatomy\?\.profile/,'target labels must use per-exercise anatomy mapping');
assert.match(detail,/Rest \$\{s\.rest\}/,'each exercise row must show a rest prescription');
assert.doesNotMatch(detail,/renderHome|updateChrome|renderProgress|renderSettings/,'Workout detail module must not become a second presentation root');
assert.match(base,/--mlc-purple/i,'base chrome must define the MYLIFTCOACH purple token');
assert.match(base,/#0/i,'base chrome must contain dark surfaces');
assert.doesNotMatch(detail,/new\s+MutationObserver/,'detail ownership must not add a document mutation observer');
console.log('MYLIFTCOACH retired-root and migrated workout-detail ownership checks: OK');
