const assert=require('assert');
global.window=global;let owner='steady-6';
global.myliftcoachIntelligenceCore={account:()=>({valid:true,owner})};
const mk=(type,id='p')=>({id,type,exerciseIds:['press','row'],reason:'evidence',confidence:.82,changes:type==='temporary_volume_reduction'?{setDelta:-1,durationExposures:2,minWorkingSets:1,noLoadIncrease:true}:{durationExposures:2,maxSetReductionPerExercise:1,noScheduleChange:true,noTrainingDayChange:true,noSplitChange:true,noLoadIncrease:true},requiresApproval:true,autoApply:false,reversible:true});
global.myliftcoachProgramAdaptationPlan=()=>({version:'8.7',state:'proposed',proposals:owner.startsWith('steady')?[]:owner.startsWith('strained')?[mk('reduced_pressure_block')]:[mk('temporary_volume_reduction')],suppressedByOutcomeHistory:[]});
global.myliftcoachAdaptiveProgramPlanReview=plan=>({version:'8.7',state:plan.proposals.length?'review_ready':'no_change',approved:plan.proposals,rejected:[]});
global.myliftcoachWeekState=()=>({available:true,applied:owner.startsWith('strained')?[1,2,3,4]:owner.startsWith('variable')?[1,2]:[]});
global.prismAdaptiveNextSession=()=>({weeklyCoordination:{weeklyStrain:!owner.startsWith('steady')},workoutCoordination:{systemicStrain:owner.startsWith('strained')},prescriptions:[]});
global.prismCoachProgramReview=()=>({evidence:{signal:owner.startsWith('strained')?'recovery':owner.startsWith('variable')?'mixed':'progressing'}});
require('../myliftcoach-adaptive-program-planning-v10.js');
const weeks=[6,12,16,20],report={};for(const w of weeks){owner=`steady-${w}`;const steady=myliftcoachAdaptiveProgramPlanV10({exerciseIds:['press','row']});assert.equal(steady.state,'observe');assert.equal(steady.proposals.length,0);owner=`strained-${w}`;const strained=myliftcoachAdaptiveProgramPlanV10({exerciseIds:['press','row']});assert.equal(strained.state,'program_review_priority');assert.equal(strained.primary.action,'review_recovery_block');assert.ok(strained.proposals.every(x=>x.horizonExposures<=2&&x.requiresApproval&&!x.autoApply));owner=`variable-${w}`;const variable=myliftcoachAdaptiveProgramPlanV10({exerciseIds:['press','row']});assert.equal(variable.state,'program_review_priority');assert.equal(variable.primary.action,'review_temporary_volume_reduction');assert.equal(variable.proposals[0].changes.setDelta,-1);owner=`steady-${w}`;const steadyAgain=myliftcoachAdaptiveProgramPlanV10({exerciseIds:['press','row']});assert.equal(steadyAgain.proposals.length,0);report[w]={steady:'observe',strained:'recovery_block_review',variable:'temporary_volume_reduction_review',isolation:true};}
console.log(JSON.stringify({suite:'MYLIFTCOACH V10 Adaptive Program-Level 6/12/16/20 Week Multi-Athlete Simulation',weeks,report,checks:{stableAthleteNotOveradapted:true,strainedAthleteGetsBoundedReview:true,variableAthleteGetsTargetedReview:true,approvalAlwaysRequired:true,noAutomaticProgramRewrite:true,noScheduleMutation:true,noSetIncrease:true,accountIsolation:true,adaptiveAuthorityPreserved:true}},null,2));
