const assert=require('node:assert/strict');
const {create}=require('../persistence/scoped-storage.js');
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const raw=new Map([['prismLocalProfileV1','{"displayName":"Local guest"}'],['workoutHistoryV52','[{"id":1}]'],['prismEntitlementV1','{"tier":"free"}']]);
const backing={getItem:k=>raw.get(k)??null,setItem:(k,v)=>raw.set(k,v),removeItem:k=>raw.delete(k)};
const manager=create(backing);
assert.equal(manager.storage.getItem('prismLocalProfileV1'),'{"displayName":"Local guest"}');
manager.select(A);
assert.equal(manager.storage.getItem('workoutHistoryV52'),null,'unclaimed guest data is never silently associated with A');
assert.equal(manager.claimGuest(),2);
manager.storage.setItem('prismLocalProfileV1','{"displayName":"A"}');
manager.storage.setItem('prismEntitlementV1','{"tier":"pro"}');
manager.select(B);
assert.equal(manager.storage.getItem('prismLocalProfileV1'),null,'A data is invisible to B');
assert.equal(manager.storage.getItem('prismEntitlementV1'),null,'beta access does not cross accounts');
manager.install({prismLocalProfileV1:'{"displayName":"B"}',workoutHistoryV52:'[]'});
assert.throws(()=>manager.install({prismLocalProfileV1:'{"displayName":"Different"}',prismCoachFeedbackV1:'[]'}),/differs/);
assert.equal(manager.storage.getItem('prismCoachFeedbackV1'),null,'conflict causes zero partial writes');
assert.throws(()=>manager.install({prismSupabaseSessionV1:'unsafe'}),/Unrecognized/);
manager.select(A);
assert.equal(manager.storage.getItem('prismLocalProfileV1'),'{"displayName":"A"}');
assert.equal(manager.storage.getItem('workoutHistoryV52'),'[{"id":1}]');
assert.equal(raw.get('prismLocalProfileV1'),'{"displayName":"Local guest"}','legacy data is untouched');
manager.select(null);
assert.equal(manager.storage.getItem('prismLocalProfileV1'),'{"displayName":"Local guest"}');
console.log('Account-local storage: explicit guest claim, A/B isolation, conflict safety, beta isolation and legacy retention OK.');
